import {comparison} from '../lib/analytics-report.js';
import {seoReportHtml,seoEmailCopy,seoWins} from '../lib/seo-report-view.js';
import {countEnquiries} from '../lib/enquiry-import.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>v==null?'—':Number(v).toLocaleString('en-GB',{maximumFractionDigits:1});
const format=(v,type='number')=>v==null?'—':type==='rate'?(v*100).toFixed(1)+'%':type==='position'?v.toFixed(1):type==='seconds'?Math.round(v)+' sec':number(v);
const date=s=>new Date(s+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
let current=null,report=null,running=false,connected=false,stopRequested=false,notesDirty=false,properties=[];
async function api(route,body){const r=await fetch('/admin/analytics-reports/api/'+route,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let d;try{d=await r.json();}catch{throw Error('The server response could not be read. Reopen the saved report to continue.');}if(!r.ok)throw Error(d.error||'The report request failed.');return d;}
function notice(message){$('notice').textContent=message||'';$('notice').hidden=!message;}
function chooseSearch(){const p=properties.find(p=>p.property===$('property').value);$('site').value=/^nc\s*digital/i.test(p?.name||'')&&[...$('site').options].some(o=>o.value==='sc-domain:nc-digital.co.uk')?'sc-domain:nc-digital.co.uk':'';}
async function connection(){const p=$('property').value,s=$('site').value,d=await api('connection');connected=d.connected;properties=d.properties;$('property').innerHTML='<option value="">Choose a client property…</option>'+properties.sort((a,b)=>a.name.localeCompare(b.name)).map(p=>`<option value="${esc(p.property)}">${esc(p.name)} · ${esc(p.property.split('/')[1])} · ${esc(p.account)}</option>`).join('');$('site').innerHTML='<option value="">Analytics only</option>'+d.sites.sort().map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');$('property').value=properties.some(x=>x.property===p)?p:properties.find(x=>/^nc\s*digital/i.test(x.name))?.property||'';chooseSearch();if(d.sites.includes(s))$('site').value=s;$('connection').textContent=connected?`${properties.length} Analytics properties · read-only access${d.searchMessage?' · '+d.searchMessage:''}`:d.message;$('start').disabled=!connected||running;}
async function history(){const d=await api('history');$('saved').innerHTML='<option value="">Choose a report…</option>'+d.reports.map(r=>`<option value="${esc(r.id)}">${esc(r.title)} · ${esc(r.status)}</option>`).join('');if(current)$('saved').value=current.id;return d.reports;}
const stageNames={overview:'Website totals',organic:'Organic search traffic',channels:'Acquisition channels',sources:'Traffic sources',landing:'Landing pages',devices:'Devices',countries:'Countries',events:'Events and key events',trend:'Daily traffic',gscCurrentTotals:'Current Google search totals',gscPreviousTotals:'Previous Google search totals',gscCurrentPages:'Current search pages',gscPreviousPages:'Previous search pages',gscCurrentQueries:'Current search queries',gscPreviousQueries:'Previous search queries',gscCurrentTrend:'Current search trend',gscPreviousTrend:'Previous search trend'};
function progress(){if(!current)return;$('progress').hidden=current.status!=='running';$('phase').textContent=stageLabel(current.stages?.[current.stage])||'Preparing the client report';$('progress-copy').textContent=`Step ${Math.min(current.stage+1,current.stages.length+1)} of ${current.stages.length+1}. Each completed step is saved.`;$('meter').max=current.stages.length+1;$('meter').value=current.stage;$('resume').hidden=running||current.status!=='running';}
function cards(source){return report.cards.filter(c=>c.source===source).map(c=>`<article class="metric-card"><h3>${esc(c.label)}</h3><div class="metric-value">${format(c.current,c.type)}</div><div class="metric-previous">Previous: ${format(c.previous,c.type)}</div><span class="change ${c.change.direction}">${esc(c.change.text)}</span>${c.daily&&report.periods.currentDays!==report.periods.previousDays?`<p class="daily">Per day: ${number(c.daily.current)} vs ${number(c.daily.previous)} · ${esc(comparison(c.daily.current,c.daily.previous).text)}</p>`:''}<details><summary>What this means</summary><p>${esc(c.insight)}</p><p>${esc(c.explanation)}</p></details></article>`).join('');}
function table(title,headers,rows,note){return `<section class="table-panel"><h3>${esc(title)}</h3><p>${esc(note)}</p>${rows.length?`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,20).map((row,i)=>`<tr ${i>=10?'class="print-extra"':''}>${row.map(cell=>`<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<p class="empty-row">No rows were returned for this selection. This does not establish that there was no activity.</p>'}</section>`;}
function pairs(kind,dimension){const groups=new Map();for(const r of report.data[kind]?.rows||[]){const key=r.dimensions[dimension],period=r.dimensions.dateRange;if(!['current','previous'].includes(period))continue;const item=groups.get(key)||{key,current:null,previous:null};item[period]=r.metrics;groups.set(key,item);}return [...groups.values()].sort((a,b)=>(b.current?.sessions??b.current?.eventCount??0)-(a.current?.sessions??a.current?.eventCount??0));}
const changeCell=(a,b,type)=>{const c=comparison(a,b,type);return `<span class="${c.direction}">${esc(c.text)}</span>`;};
function sessionTable(kind,dimension,title){return table(title,['Channel / source / page','Sessions','Previous','Change','Engagement rate','Key events'],pairs(kind,dimension).map(r=>[esc(r.key),number(r.current?.sessions),number(r.previous?.sessions),changeCell(r.current?.sessions,r.previous?.sessions),`${format(r.current?.engagementRate,'rate')}<small>Previous: ${format(r.previous?.engagementRate,'rate')}</small>`,`${number(r.current?.keyEvents)}<small>Previous: ${number(r.previous?.keyEvents)}</small>`]),'Top 20 returned entries by current sessions (top 10 in PDF). Missing prior rows are unknown, not zero. Totals can differ from the sum of these rows.');}
function searchTable(kind,title){const groups=new Map();for(const period of ['Current','Previous'])for(const r of report.data['gsc'+period+kind]?.rows||[]){const key=r.keys[0],item=groups.get(key)||{key};item[period.toLowerCase()]=r;groups.set(key,item);}const rows=[...groups.values()].sort((a,b)=>(b.current?.clicks||0)-(a.current?.clicks||0)||(b.current?.impressions||0)-(a.current?.impressions||0));return table(title,[kind==='Pages'?'Page':'Query','Clicks','Impressions','CTR','Avg. position','Click change'],rows.map(r=>[esc(r.key),`${number(r.current?.clicks)}<small>Previous: ${number(r.previous?.clicks)}</small>`,`${number(r.current?.impressions)}<small>Previous: ${number(r.previous?.impressions)}</small>`,`${format(r.current?.ctr,'rate')}<small>Previous: ${format(r.previous?.ctr,'rate')}</small>`,`${format(r.current?.position,'position')}<small>Previous: ${format(r.previous?.position,'position')}</small>`,changeCell(r.current?.clicks,r.previous?.clicks)]),'Top 20 returned entries by current clicks, then impressions (top 10 in PDF). Google can withhold anonymised queries; a missing row does not prove zero traffic.');}
function trend(){const rows=(report.data.trend?.rows||[]).map(r=>({date:r.dimensions.date?.replace(/^(\d{4})(\d{2})(\d{2})$/,'$1-$2-$3'),period:r.dimensions.dateRange,sessions:r.metrics.sessions})).filter(r=>/^\d{4}-\d{2}-\d{2}$/.test(r.date||'')&&r.sessions!=null);if(!rows.length){$('trend').innerHTML='<p class="muted">No daily rows were returned.</p>';return;}const start=Date.parse(report.periods.previous.startDate),end=Date.parse(report.periods.current.endDate),max=Math.max(1,...rows.map(r=>r.sessions)),x=d=>25+(Date.parse(d)-start)/(end-start)*970,y=n=>160-n/max*140;const lines=['previous','current'].map(p=>`<polyline points="${rows.filter(r=>r.period===p).sort((a,b)=>a.date.localeCompare(b.date)).map(r=>`${x(r.date)},${y(r.sessions)}`).join(' ')}" fill="none" stroke="${p==='previous'?'#888092':'#b283df'}" stroke-width="2"/>`).join('');$('trend').innerHTML=`<svg viewBox="0 0 1020 180" role="img" aria-label="Daily sessions for the previous and current reporting periods"><text x="1" y="15" fill="#a28ab5" font-size="10">${max}</text><line x1="25" x2="995" y1="160" y2="160" stroke="#53455e"/><line x1="${x(report.periods.current.startDate)}" x2="${x(report.periods.current.startDate)}" y1="20" y2="160" stroke="#796b86" stroke-dasharray="3 5"/>${lines}${rows.map(r=>`<circle cx="${x(r.date)}" cy="${y(r.sessions)}" r="2" fill="${r.period==='current'?'#b283df':'#888092'}"><title>${r.date}: ${r.sessions} sessions</title></circle>`).join('')}</svg><div class="trend-labels"><span>${date(report.periods.previous.startDate)}</span><span>${date(report.periods.current.startDate)}</span><span>${date(report.periods.current.endDate)}</span></div><p class="muted">Only returned dates are plotted; omitted dates are not treated as measured zeroes.</p>`;}
function render(){if(!current?.report){report=null;$('report').hidden=true;$('empty').hidden=false;progress();return;}report=current.report;$('report').hidden=false;$('empty').hidden=true;const p=report.periods;$('report-title').textContent=report.property.name;$('dates').textContent=`${date(p.current.startDate)} – ${date(p.current.endDate)} (${p.currentDays} days) · compared with ${date(p.previous.startDate)} – ${date(p.previous.endDate)} (${p.previousDays} days)`;$('scope').textContent=`GA4 ${report.property.id.split('/')[1]} · ${report.input.country==='gbr'?'United Kingdom':'All countries'} · Web traffic · Analytics time zone: ${p.timeZone}`;$('warnings').innerHTML=report.warnings.map(w=>`<p class="warning">${esc(w)}</p>`).join('');
 const summary=report.cards.filter(c=>(c.source==='gsc'&&c.key==='clicks')||(c.source==='ga'&&['sessions','keyEvents'].includes(c.key)));$('summary').innerHTML=`<div class="summary-grid">${summary.map(c=>`<div><strong>${esc(c.label)}: ${format(c.current,c.type)}</strong><p><span class="${c.change.direction}">${esc(c.change.text)}</span> vs ${format(c.previous,c.type)} previously.</p><p>${esc(c.insight)}</p></div>`).join('')}</div>`;
 $('search-section').hidden=!report.input.site;document.querySelector('a[href="#search-section"]').hidden=!report.input.site;$('search-property').textContent=report.input.site||'Not included';$('search-cards').innerHTML=cards('gsc');$('website-cards').innerHTML=cards('ga');$('organic-cards').innerHTML=cards('organic');$('search-tables').innerHTML=report.input.site?searchTable('Queries','Google search queries')+searchTable('Pages','Pages appearing in Google search'):'';
 $('acquisition-tables').innerHTML=sessionTable('channels','sessionDefaultChannelGroup','Acquisition channels')+sessionTable('sources','sessionSourceMedium','Sources / mediums');$('landing-table').innerHTML=sessionTable('landing','landingPage','Landing page performance');
 $('audience-tables').innerHTML=table('Recorded events',['Event name','Event count','Previous count','Key events','Previous key events'],pairs('events','eventName').map(r=>[esc(r.key),number(r.current?.eventCount),number(r.previous?.eventCount),number(r.current?.keyEvents),number(r.previous?.keyEvents)]),'Not every event is a key event. Verify form, call and purchase tracking before using these counts as business outcomes.')+sessionTable('devices','deviceCategory','Device performance')+sessionTable('countries','country','Visitor countries');
 $('notes').value=current.notes||'';$('work').value=current.work||'';$('print-notes').textContent=current.notes||'No additional commentary supplied.';notesDirty=false;$('notes-status').textContent='';$('generated').textContent=`Generated ${new Date(report.generatedAt).toLocaleString('en-GB')} · NC Digital · Report ${current.id}`;trend();progress();renderClient();}
// The plain-English client report (what prints) and the website-form enquiry figures behind it.
function renderClient(){if(!current?.report)return;$('client-doc').innerHTML=seoReportHtml(current,{forms:current.forms});renderSeoShare();const f=current.forms;$('enq-current').value=f?.current??'';$('enq-previous').value=f?.previous??'';$('enq-status').textContent=f?`Saved: ${f.current} this period${f.previous!=null?`, ${f.previous} in the previous period`:''}${f.file?` (from ${f.file})`:''}.`:'No website form enquiries added yet.';}
let enqImport=null;
$('enq-file').addEventListener('change',async()=>{const file=$('enq-file').files[0];if(!file||!current?.report)return;try{const counted=countEnquiries(await file.text(),current.report.periods);enqImport={file:file.name,column:counted.column};$('enq-current').value=counted.current;$('enq-previous').value=counted.previous;$('enq-status').textContent=`Found ${counted.entries} entries using the “${counted.column}” column: ${counted.current} in this period and ${counted.previous} in the previous period${counted.unreadable?` (${counted.unreadable} had no readable date)`:''}. Check the numbers, then save.`;}catch(e){enqImport=null;$('enq-status').textContent=e.message;}finally{$('enq-file').value='';}});
$('enq-save').addEventListener('click',async()=>{if(!current?.report)return;try{if($('enq-current').value==='')throw Error('Enter the number of enquiries for this period, or choose a CSV export.');const d=await api('enquiries',{id:current.id,current:Number($('enq-current').value),previous:$('enq-previous').value===''?null:Number($('enq-previous').value),file:enqImport?.file||current.forms?.file||'',column:enqImport?.column||current.forms?.column||''});current.forms=d.forms;enqImport=null;renderClient();}catch(e){$('enq-status').textContent=e.message;}});
$('enq-clear').addEventListener('click',async()=>{if(!current?.report)return;try{await api('enquiries',{id:current.id,current:null});current.forms=null;enqImport=null;renderClient();}catch(e){$('enq-status').textContent=e.message;}});
async function saveNotes(){if(!notesDirty||!current?.report)return;await api('notes',{id:current.id,notes:$('notes').value});await api('work',{id:current.id,work:$('work').value});current.notes=$('notes').value;current.work=$('work').value;notesDirty=false;$('notes-status').textContent='Saved';$('print-notes').textContent=current.notes||'No additional commentary supplied.';renderClient();}
async function run(){if(running||!current)return;running=true;stopRequested=false;$('fields').disabled=true;$('open').disabled=true;notice('');try{while(current.status==='running'&&!stopRequested){progress();current=await api('advance',{id:current.id});}if(stopRequested&&current.status==='running')current=await api('stop',{id:current.id});await history();render();if(current.status==='stopped')notice('Report stopped. Start a new report when you are ready.');}catch(e){notice(e.message+' Completed steps are saved; use Resume to retry.');}finally{running=false;$('fields').disabled=false;$('open').disabled=false;$('start').disabled=!connected;progress();}}
async function open(id){if(running)return;await saveNotes();current=await api('report?id='+encodeURIComponent(id));window.history.replaceState(null,'','?report='+current.id);notice(current.status==='stopped'?'This report was stopped. Start a new report to complete the comparison.':'');render();}
function dates(){const custom=$('period').value==='custom';$('custom-dates').hidden=!custom;for(const id of ['start-date','end-date'])$(id).required=custom;}
const localDate=new Date();localDate.setDate(localDate.getDate()-1);$('end-date').value=localDate.toISOString().slice(0,10);localDate.setDate(localDate.getDate()-29);$('start-date').value=localDate.toISOString().slice(0,10);
$('period').addEventListener('change',dates);$('property').addEventListener('change',chooseSearch);$('refresh-connection').addEventListener('click',async()=>{try{await connection();}catch(e){notice(e.message);}});
$('form').addEventListener('submit',async e=>{e.preventDefault();if(running)return;$('start').disabled=true;try{await saveNotes();current=await api('start',{property:$('property').value,site:$('site').value,period:$('period').value,startDate:$('start-date').value,endDate:$('end-date').value,country:$('country').value,refresh:$('fresh').checked});window.history.replaceState(null,'','?report='+current.id);$('report').hidden=true;$('empty').hidden=true;const cached=current.cached,resumed=current.resumed;await run();if(cached)notice('Opened the saved report. No new Analytics or Search Console report queries were needed.');else if(resumed)notice('Resumed the unfinished report before starting another. Check the property and dates in its heading.');}catch(e){notice(e.message);$('start').disabled=!connected;}});
$('open').addEventListener('click',async()=>{if(!$('saved').value)return;try{await open($('saved').value);}catch(e){notice(e.message);}});$('resume').addEventListener('click',run);$('stop').addEventListener('click',async()=>{stopRequested=true;if(!running&&current){try{current=await api('stop',{id:current.id});render();await history();notice('Report stopped. Start a new report to try again.');}catch(e){notice(e.message);}}});
$('work').addEventListener('input',()=>{notesDirty=true;$('notes-status').textContent='Unsaved changes';});
// Suggest pages that started appearing in Google this period, as readable titles from their addresses.
$('work-suggest').addEventListener('click',()=>{if(!current?.report)return;const wins=seoWins(current.report),pages=(wins?.newPages||[]).map(p=>p.path.replace(/^\/|\/$/g,'').split('/').pop().replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase())).filter(Boolean);if(!pages.length){$('notes-status').textContent='No new pages were found in Search Console for this period.';return;}const existing=$('work').value.trim();$('work').value=(existing?existing+'\n\n':'')+'New pages appearing in Google:\n'+pages.join('\n');notesDirty=true;$('notes-status').textContent=`Added ${pages.length} page${pages.length===1?'':'s'}. Edit the list, then save.`;});
$('notes').addEventListener('input',()=>{notesDirty=true;$('notes-status').textContent='Unsaved changes';$('print-notes').textContent=$('notes').value;});$('save-notes').addEventListener('click',async()=>{try{await saveNotes();}catch(e){$('notes-status').textContent=e.message;}});window.addEventListener('beforeunload',e=>{if(notesDirty){e.preventDefault();e.returnValue='';}});
$('print').addEventListener('click',async()=>{try{await saveNotes();document.title=`${report.property.name} — SEO report — ${report.periods.current.startDate} to ${report.periods.current.endDate}`;for(const d of document.querySelectorAll('.metric-card details'))d.open=true;await document.fonts.ready;window.print();}catch(e){notice(e.message);}});
$('export').addEventListener('click',()=>{if(!report)return;const scope=[report.property.name,report.property.id,report.input.site,report.input.country,report.periods.current.startDate,report.periods.current.endDate,report.periods.previous.startDate,report.periods.previous.endDate];const rows=[['Client','GA4 property','Search Console property','Country','Current start','Current end','Previous start','Previous end','Source','Metric / dimension','Current','Previous','Change','Explanation']];for(const c of report.cards)rows.push([...scope,c.source,c.label,c.current,c.previous,c.change.text,c.explanation+' '+c.insight]);for(const [kind,dimension]of [['channels','sessionDefaultChannelGroup'],['sources','sessionSourceMedium'],['landing','landingPage'],['devices','deviceCategory'],['countries','country'],['events','eventName']])for(const r of pairs(kind,dimension))for(const metric of kind==='events'?['eventCount','keyEvents']:['sessions','engagementRate','keyEvents'])rows.push([...scope,'GA4 '+kind,r.key+' / '+metric,r.current?.[metric],r.previous?.[metric],comparison(r.current?.[metric],r.previous?.[metric],metric==='engagementRate'?'rate':'number').text,'Rates are fractions in this export. Missing values remain blank.']);const cell=x=>'"'+String(x??'').replace(/^[\s]*[=+@-]/,"'$&").replaceAll('"','""')+'"';const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='nc-digital-client-report.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
// ---- Saved clients: set up once, then create each month's report in one click.
let clients=[];
const stageLabel=kind=>stageNames[kind]||(String(kind||'').startsWith('rankings:')?'Checking Google rankings for tracked searches':undefined);
async function loadClients(select){try{const d=await api('clients');clients=d.clients;$('client-select').innerHTML='<option value="">Choose a saved client…</option>'+clients.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');if(select!==undefined)$('client-select').value=select;clientSummary();}catch(e){$('client-summary').textContent=e.message;}}
const selectedClient=()=>clients.find(c=>c.id===$('client-select').value)||null;
function clientSummary(){const c=selectedClient();$('client-run').disabled=!c||running||!connected;$('client-edit').disabled=!c;
  $('client-summary').textContent=c?[c.site?c.site.replace('sc-domain:',''):'Analytics only',c.keywords.length?`${c.keywords.length} tracked search${c.keywords.length===1?'':'es'} in ${String(c.locationName||'').split(',')[0]}`:'No tracked searches',c.contactEmail?'Reports go to '+c.contactEmail:''].filter(Boolean).join(' · '):'Save a client once to create each month’s report in one click.';}
function openClientForm(c){$('client-form').hidden=false;$('client-form-title').textContent=c?'Edit '+c.name:'New client';$('c-property').innerHTML=$('property').innerHTML;$('c-site').innerHTML=$('site').innerHTML;
  $('c-name').value=c?.name||'';$('c-property').value=c?.property||$('property').value;$('c-site').value=c?c.site:$('site').value;$('c-country').value=c?.country||'all';$('c-town').value=c?.locationName||'';$('c-contact-name').value=c?.contactName||'';$('c-contact-email').value=c?.contactEmail||'';
  $('c-keywords').value=(c?.keywords||[]).join('\n');$('c-brand').value=(c?.brandTerms||[]).join('\n');$('c-events').value=(c?.enquiryEvents||[]).join('\n');$('client-delete').hidden=!c;$('client-form').dataset.id=c?.id||'';
  const events=[...new Set((current?.report?.data?.events?.rows||[]).map(r=>r.dimensions.eventName).filter(Boolean))];$('c-events-hint').textContent=events.length?'Events in the open report: '+events.join(', '):'';$('client-status').textContent='';$('c-name').focus();}
$('client-select').addEventListener('change',clientSummary);
$('client-new').addEventListener('click',()=>openClientForm(null));
$('client-edit').addEventListener('click',()=>openClientForm(selectedClient()));
$('client-cancel').addEventListener('click',()=>{$('client-form').hidden=true;});
$('client-form').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('client',{id:$('client-form').dataset.id||undefined,name:$('c-name').value,property:$('c-property').value,site:$('c-site').value,country:$('c-country').value,town:$('c-town').value,contactName:$('c-contact-name').value,contactEmail:$('c-contact-email').value,keywords:$('c-keywords').value,brandTerms:$('c-brand').value,enquiryEvents:$('c-events').value});$('client-form').hidden=true;await loadClients(d.client.id);notice(`Saved ${d.client.name}. Choose “Create last month’s report” whenever you need it.`);}catch(err){$('client-status').textContent=err.message;}});
$('client-delete').addEventListener('click',async()=>{const id=$('client-form').dataset.id;if(!id)return;try{await api('client-delete',{id});$('client-form').hidden=true;await loadClients('');}catch(err){$('client-status').textContent=err.message;}});
let townVersion=0;$('c-town').addEventListener('input',async()=>{const version=++townVersion,q=$('c-town').value;if(q.length<2)return;try{const r=await fetch('/admin/keyword-research/api/locations?q='+encodeURIComponent(q)).then(x=>x.json());if(version===townVersion)$('c-towns').innerHTML=(r.locations||[]).map(x=>`<option value="${esc(x.name)}">${esc(x.type)}</option>`).join('');}catch{}});
async function startWith(body){if(running)return;try{await saveNotes();current=await api('start',body);window.history.replaceState(null,'','?report='+current.id);$('report').hidden=true;$('empty').hidden=true;const cached=current.cached;await run();if(cached)notice('Opened the report already created today. Tick “Refresh saved data” to run it again.');}catch(e){notice(e.message);}finally{clientSummary();}}
$('client-run').addEventListener('click',()=>{const c=selectedClient();if(c)startWith({clientId:c.id,period:'1',refresh:$('fresh').checked});});

// ---- Client link and emailing the report from the CRM mailbox.
let seoEmailEdited=false,seoEmailKey=null;
const keepForms=d=>({...current,...d,forms:current.forms});
function renderSeoShare(){if(!current?.report)return;const s=current.share;$('seo-share-panel').hidden=!s;$('seo-share').textContent=s?'Client link ✓':'Create client link';
  if(s){$('seo-share-url').value=s.url;$('seo-share-open').href=s.url+'?preview=1';$('seo-share-stats').textContent=s.views?`Opened ${s.views} time${s.views===1?'':'s'} · last ${new Date(s.lastViewedAt).toLocaleString('en-GB')}.`:`Created ${new Date(s.createdAt).toLocaleDateString('en-GB')} · not opened yet.`;}
  const sent=current.emails||[];$('seo-email-history').innerHTML=sent.length?'<p class="eyebrow">SENT</p>'+sent.slice().reverse().map(e=>`<p>Emailed to <strong>${esc(e.name?e.name+' · ':'')}${esc(e.to)}</strong> · ${new Date(e.at).toLocaleDateString('en-GB')} · <a href="/admin/crm/?ticket=${encodeURIComponent(e.ticketId)}">${esc(e.reference)} in the CRM →</a></p>`).join(''):'';}
const seoCopy=()=>seoEmailCopy(current,$('seo-email-name').value,current.share?.url||'');
$('seo-share').addEventListener('click',async()=>{if(!current?.report)return;try{await saveNotes();current=keepForms(await api('share',{id:current.id,enable:true}));renderSeoShare();try{await navigator.clipboard.writeText(current.share.url);notice('Client link created and copied.');}catch{}}catch(e){notice(e.message);}});
$('seo-share-copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('seo-share-url').value);$('seo-share-copy').textContent='Copied ✓';setTimeout(()=>{$('seo-share-copy').textContent='Copy link';},2000);}catch{$('seo-share-url').select();}});
$('seo-share-off').addEventListener('click',async()=>{try{current=keepForms(await api('share',{id:current.id,enable:false}));renderSeoShare();notice('The client link has been turned off.');}catch(e){notice(e.message);}});
$('seo-email-open').addEventListener('click',async()=>{if(!current?.report)return;try{await saveNotes();if(!current.share)current=keepForms(await api('share',{id:current.id,enable:true}));renderSeoShare();$('seo-email-panel').hidden=false;
  if(!$('seo-email-to').value)$('seo-email-to').value=current.client?.contactEmail||'';if(!$('seo-email-name').value)$('seo-email-name').value=current.client?.contactName||'';if(!seoEmailEdited)$('seo-email-message').value=seoCopy();seoEmailKey=seoEmailKey||crypto.randomUUID();$('seo-email-status').textContent='';$('seo-email-panel').scrollIntoView({behavior:'smooth',block:'nearest'});}catch(e){notice(e.message);}});
$('seo-email-close').addEventListener('click',()=>{$('seo-email-panel').hidden=true;});
$('seo-email-name').addEventListener('input',()=>{if(!seoEmailEdited)$('seo-email-message').value=seoCopy();});
$('seo-email-message').addEventListener('input',()=>{seoEmailEdited=true;});
$('seo-email-form').addEventListener('submit',async e=>{e.preventDefault();$('seo-email-send').disabled=true;$('seo-email-status').textContent='Sending…';
  try{current=keepForms(await api('email',{id:current.id,name:$('seo-email-name').value,email:$('seo-email-to').value,message:$('seo-email-message').value,request_key:seoEmailKey}));seoEmailKey=null;seoEmailEdited=false;$('seo-email-status').textContent='Queued: it sends from your mailbox within a minute.';renderSeoShare();}
  catch(err){$('seo-email-status').textContent=err.message;}finally{$('seo-email-send').disabled=false;}});
(async()=>{dates();const results=await Promise.allSettled([connection(),history()]);for(const r of results)if(r.status==='rejected')notice(r.reason.message);const saved=results[1].status==='fulfilled'?results[1].value:[],id=new URLSearchParams(location.search).get('report')||saved.find(r=>r.status==='running')?.id;if(id)try{await open(id);}catch(e){notice(e.message);}await loadClients();})();
