import {parseGapInput} from '../lib/competitor-gaps.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>v==null?'—':Number(v).toLocaleString('en-GB',{maximumFractionDigits:0}),money=v=>'$'+Number(v||0).toFixed(4),when=s=>s?new Date(s.replace(' +00:00','Z').replace(' ','T')).toLocaleDateString('en-GB'):'Not supplied';
let current=null,report=null,running=false,connected=false,stopRequested=false,quote=null,version=0,custom=[],tasks=new Map(),visible=[],selected=null;
async function api(route,body){const r=await fetch('/admin/competitor-gaps/api/'+route,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let d;try{d=await r.json();}catch{throw Error('The response could not be read. Open saved research before retrying.');}if(!r.ok)throw Error(d.error||'Comparison request failed.');return d;}
function notice(message){$('notice').hidden=!message;$('notice').textContent=message||'';}
function input(){return {client:$('client').value,competitors:$('competitors').value,focus:$('focus').value,brands:$('brands').value,limit:Number($('limit').value),minVolume:Number($('volume').value),maxRank:Number($('rank').value),budget:Number($('budget').value),refresh:$('fresh').checked};}
async function status(){const s=await api('status');connected=s.connected;custom=s.customExclusions;$('connection').textContent=connected?'DataForSEO connected · UK organic search':'DataForSEO is not connected';$('daily').textContent=`${money(s.daily.remaining)} of $${s.daily.limit.toFixed(2)} remaining in the rolling 24-hour allowance`;$('excluded-count').textContent=`· ${s.directories.length+custom.length} rules`;$('custom-exclusions').textContent=custom.length?'Additional exclusions: '+custom.join(', '):'No additional directory exclusions yet.';$('preview').disabled=!connected||running;}
async function history(){const d=await api('history');$('saved').innerHTML='<option value="">Choose a report…</option>'+d.reports.map(r=>`<option value="${esc(r.id)}">${esc(r.title)} · ${esc(r.status)}</option>`).join('');if(current)$('saved').value=current.id;return d.reports;}
function progress(){if(!current)return;$('progress').hidden=current.status!=='running';const step=current.steps[current.index];$('phase').textContent=step?`${step.competitor} · ${step.kind==='missing'?'client not observed':'shared rankings'}`:'Building your page plan';$('progress-copy').textContent=`${current.index} of ${current.steps.length} lookups processed · ${money(current.actual)} confirmed · ${money(current.committed)} spent or reserved`;$('resume').hidden=running||current.status!=='running';}
function renderRows(){if(!report)return;const q=$('search').value.toLowerCase(),type=$('type').value,work=$('status-filter').value,sort=$('sort').value;visible=report.opportunities.map((o,index)=>({...o,index})).filter(o=>(!q||o.keyword.includes(q))&&(type==='all'||o.type===type)&&(work==='all'||(work==='active'?!['done','dismissed'].includes(tasks.get(o.keyword)?.status):tasks.get(o.keyword)?.status===work))).sort((a,b)=>sort==='difficulty'?(a.difficulty??101)-(b.difficulty??101):sort==='volume'?(b.volume??-1)-(a.volume??-1):b.score-a.score);$('count').textContent=visible.length+' keywords';$('rows').innerHTML=visible.map(o=>`<tr><td><strong>${esc(o.keyword)}</strong><small>${esc(o.action)}</small><small>Priority ${o.score}/100 · ${esc((tasks.get(o.keyword)?.status||'to-do').replaceAll('-',' '))}</small></td><td>${number(o.volume)}</td><td>${number(o.difficulty)}</td><td>${o.client?number(o.client.rank):'<span class="badge">Not observed</span>'}</td><td>${o.bestCompetitorRank}<small>${o.competitorCount} business${o.competitorCount===1?'':'es'}</small></td><td><button data-inspect="${o.index}">Inspect ↗</button></td></tr>`).join('');$('no-results').hidden=visible.length>0;}
function renderPlans(){if(!report)return;$('plans').innerHTML=report.plans.length?report.plans.map(p=>`<article class="panel gap-plan"><span class="badge">${esc(p.action)}</span><h3>${esc(p.title)}</h3>${p.page?`<p>Page to review: <a href="${esc(p.page)}" target="_blank" rel="noopener noreferrer">${esc(p.page)}</a></p>`:'<p>Check the existing website before deciding to create a new page.</p>'}<p class="keywords"><strong>Candidate keywords:</strong> ${esc(p.keywords.join(' · '))}</p><ol>${p.tasks.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>${p.keywords.map(k=>{const task=tasks.get(k);return task?`<p class="plan-notes"><strong>${esc(k)} · ${esc(task.status.replaceAll('-',' '))}</strong>\n${esc(task.notes)}</p>`:'';}).join('')}</article>`).join(''):'<p class="muted">No page opportunities met these filters. Try more relevant competitors or broader focus phrases; a small database sample is not proof of no opportunity.</p>';}
function table(title,headers,rows){return `<section class="table-panel"><h3>${esc(title)}</h3><div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`;}
async function render(){if(!current?.report){report=null;$('report').hidden=true;$('empty').hidden=false;progress();return;}report=current.report;const data=await api('tasks?client='+encodeURIComponent(report.input.client));tasks=new Map(data.tasks.map(t=>[t.keyword,t]));$('report').hidden=false;$('empty').hidden=true;$('title').textContent=report.input.client;$('scope').textContent=`Compared with ${report.input.competitors.join(', ')} · UK / English · ${when(report.generatedAt)}${report.input.focus.length?' · Focus: '+report.input.focus.join(', '):''}`;$('cost').textContent=`Confirmed charges for this report: ${money(current.actual)} USD · ${money(current.committed)} spent or reserved${current.uncertain?' · '+current.uncertain+' uncertain charge(s)':''}. Opening saved results does not repeat paid lookups.`;$('warnings').innerHTML=report.warnings.map(w=>`<p class="warning">${esc(w)}</p>`).join('');
 const missing=report.opportunities.filter(o=>o.type==='missing').length;const stats=[['Keyword opportunities',report.opportunities.length,'Deduplicated across competitors'],['Client not observed',missing,'Database finding · verify on the site'],['Existing rankings to improve',report.opportunities.length-missing,'Competitor is at least 3 positions ahead'],['Suggested page plans',report.plans.length,'Review before commissioning content']];$('stats').innerHTML=stats.map(([label,value,note])=>`<div class="gap-stat"><small>${label}</small><strong>${value}</strong><span>${note}</span></div>`).join('');
 $('coverage').innerHTML=table('Comparison coverage',['Business','Lookup','Rows returned','Total matching rows','Fetched','Source'],report.coverage.map(c=>[esc(c.competitor),c.kind==='missing'?'Client not observed':'Shared queries',`${c.returned}${c.discarded?'<small>'+c.discarded+' invalid or excluded rows removed</small>':''}`,number(c.total),when(c.fetchedAt),c.error?esc(c.error):c.cached?'Cached lookup':'Provider lookup']))+'<p>Each lookup returns a bounded shortlist ranked by search volume. More rows may exist in the provider’s database. Directories are excluded, and no additional pages are requested automatically.</p>';
 $('ledger').innerHTML=table('Paid lookup ledger',['Lookup','Allowance','Confirmed charge','Status'],current.ledger.map(l=>[esc(current.steps[l.step]?.competitor+' / '+current.steps[l.step]?.kind),money(l.reserve),l.cost==null?'Unconfirmed':money(l.cost),esc(l.status)]))+'<p>Cached lookups do not appear as new charges. Unconfirmed outcomes keep their allowance reserved and are not retried automatically.</p>';renderRows();renderPlans();progress();}
async function saveDrafts(){for(const [keyword,t]of tasks)if(t.dirty){await api('task',{id:current.id,keyword,status:t.status,notes:t.notes});t.dirty=false;}}
async function run(){if(running||!current)return;running=true;stopRequested=false;$('fields').disabled=true;$('start').disabled=true;$('open').disabled=true;notice('');try{while(current.status==='running'&&!stopRequested){progress();current=await api('advance',{id:current.id});}if(stopRequested&&current.status==='running')current=await api('stop',{id:current.id});await history();await render();await status();if(current.status==='stopped')notice('The comparison was stopped. Completed lookup caches are retained for a future run.');}catch(e){notice(e.message+' Completed work and spending reservations are saved.');}finally{running=false;$('fields').disabled=false;$('open').disabled=false;$('preview').disabled=!connected;progress();}}
async function open(id){if(running)return;await saveDrafts();current=await api('report?id='+encodeURIComponent(id));window.history.replaceState(null,'','?report='+current.id);notice(current.status==='stopped'?'This comparison was stopped. Preview a new run to reuse its completed lookup caches.':'');await render();}
$('form').addEventListener('input',()=>{version++;quote=null;$('quote').hidden=true;$('start').disabled=true;});
$('form').addEventListener('submit',async e=>{e.preventDefault();if(running)return;const v=version,payload=input();$('preview').disabled=true;notice('');try{parseGapInput(payload,custom);const p=await api('preview',payload);if(v!==version)return;quote={payload,preview:p};$('quote').hidden=false;$('quote-title').textContent=`${p.paid} paid lookup${p.paid===1?'':'s'} · ${p.cached} cached · $${p.reserve.toFixed(2)} allowance needed`;$('quote-copy').textContent=`Up to ${p.steps} lookups. Each uncached request reserves $${p.perLookupReserve.toFixed(2)} USD; confirmed charges may be lower. Your run limit is $${payload.budget.toFixed(2)}.`;$('start').disabled=p.reserve>payload.budget||p.reserve>p.daily.remaining;if($('start').disabled)$('quote-copy').textContent+=' Raise the run allowance, reduce the competitor count or wait for the daily allowance to reset.';}catch(e){notice(e.message);}finally{$('preview').disabled=!connected;}});
$('start').addEventListener('click',async()=>{if(!quote||running)return;$('start').disabled=true;try{await saveDrafts();current=await api('start',quote.payload);window.history.replaceState(null,'','?report='+current.id);$('report').hidden=true;$('empty').hidden=true;$('quote').hidden=true;const cached=current.cached,resumed=current.resumed;await run();if(cached)notice('Opened the saved comparison. No new paid lookups were needed.');else if(resumed)notice('Resumed the unfinished comparison. Check the client and competitors in the report heading.');}catch(e){notice(e.message);$('start').disabled=false;}});
$('open').addEventListener('click',async()=>{if(!$('saved').value)return;try{await open($('saved').value);}catch(e){notice(e.message);}});$('resume').addEventListener('click',run);$('stop').addEventListener('click',async()=>{stopRequested=true;if(!running&&current){try{current=await api('stop',{id:current.id});await render();await history();}catch(e){notice(e.message);}}});
$('exclude-form').addEventListener('submit',async e=>{e.preventDefault();try{await saveDrafts();const r=await api('exclude',{domain:$('exclude-domain').value});$('exclude-domain').value='';await status();if(current?.report)await open(current.id);quote=null;$('quote').hidden=true;notice(`${r.domain} is excluded, including its subdomains. Saved report results have been refreshed.`);}catch(e){notice(e.message);}});
for(const id of ['search','type','status-filter','sort'])$(id).addEventListener('input',renderRows);
function tab(name){for(const b of document.querySelectorAll('[data-tab]')){const active=b.dataset.tab===name;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;$(b.dataset.tab+'-panel').hidden=!active;}}
document.querySelectorAll('[data-tab]').forEach(b=>{b.addEventListener('click',()=>tab(b.dataset.tab));b.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const tabs=[...document.querySelectorAll('[data-tab]')],i=tabs.indexOf(b),next=e.key==='Home'?tabs[0]:e.key==='End'?tabs.at(-1):tabs[(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length];tab(next.dataset.tab);next.focus();});});
$('rows').addEventListener('click',e=>{const b=e.target.closest('[data-inspect]');if(!b)return;const o=report.opportunities[Number(b.dataset.inspect)];selected=o.keyword;const task=tasks.get(selected)||{status:'to-do',notes:''};$('task-status').value=task.status;$('task-notes').value=task.notes;$('task-message').textContent=task.dirty?'Unsaved changes':'';$('detail-body').innerHTML=`<h2>${esc(o.keyword)}</h2><p class="evidence">${esc(o.action)} · Priority ${o.score}/100</p><p>UK monthly searches: ${number(o.volume)} · Organic difficulty: ${number(o.difficulty)}/100 · CPC: ${o.cpc==null?'—':money(o.cpc)+' USD'} · Intent: ${esc(o.intent||'Unknown')}</p><p>Keyword metrics updated: ${when(o.metricsAt)}. Ranking data is a provider snapshot, not a live local search.</p>${o.mixedSnapshots?'<p class="warning">Some snapshots report no client result while others include one. The observed client ranking is used; verify the current results.</p>':''}${o.suggestedPage?`<p>${o.suggestionHeuristic?'Related page to review (title/path match)':'Observed client ranking page'}: <a href="${esc(o.suggestedPage)}" target="_blank" rel="noopener noreferrer">${esc(o.suggestedPage)}</a></p>`:'<p>No matching client page was identified in this limited sample. Check the website inventory before creating a page.</p>'}<h3>Business competitors</h3>${o.evidence.map(c=>`<article><h3>${esc(c.domain)} · organic position ${c.rank}</h3><a href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">${esc(c.url)}</a><p>${esc(c.title)}<br/>Client: ${c.client?'organic position '+c.client.rank:'not observed in this lookup'} · fetched ${when(c.at)}</p></article>`).join('')}<h3>Suggested next steps</h3><ol>${o.tasks.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>`;$('detail').showModal();});
$('close').addEventListener('click',()=>$('detail').close());$('task-form').addEventListener('input',()=>{if(!selected)return;tasks.set(selected,{status:$('task-status').value,notes:$('task-notes').value,dirty:true});$('task-message').textContent='Unsaved changes';renderPlans();});$('task-form').addEventListener('submit',async e=>{e.preventDefault();$('save-task').disabled=true;try{await saveDrafts();$('task-message').textContent='Saved';renderRows();renderPlans();}catch(e){$('task-message').textContent=e.message;}finally{$('save-task').disabled=false;}});
window.addEventListener('beforeunload',e=>{if([...tasks.values()].some(t=>t.dirty)){e.preventDefault();e.returnValue='';}});
$('print').addEventListener('click',async()=>{try{await saveDrafts();renderPlans();tab('plans');document.title='Competitor page plan — '+report.input.client;await document.fonts.ready;window.print();}catch(e){notice(e.message);}});
$('export').addEventListener('click',()=>{if(!report)return;const rows=[['Client','Country','Language','Keyword','Opportunity','Suggested action','Suggested client URL','UK monthly volume','CPC USD','Organic difficulty','Client organic position','Best competitor position','Competitor count','Competitor URLs','Priority heuristic','Metrics updated','Work status','Notes'],...visible.map(o=>{const t=tasks.get(o.keyword);return [report.input.client,'United Kingdom','English',o.keyword,o.type==='missing'?'Client not observed':'Existing ranking to improve',o.action,o.suggestedPage,o.volume,o.cpc,o.difficulty,o.client?.rank,o.bestCompetitorRank,o.competitorCount,o.evidence.map(e=>e.url).join(' | '),o.score,o.metricsAt,t?.status||'to-do',t?.notes||''];})];const cell=x=>'"'+String(x??'').replace(/^\s*[=+@-]/,"'$&").replaceAll('"','""')+'"',url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='nc-digital-competitor-gaps.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
(async()=>{const r=await Promise.allSettled([status(),history()]);for(const x of r)if(x.status==='rejected')notice(x.reason.message);const saved=r[1].status==='fulfilled'?r[1].value:[],id=new URLSearchParams(location.search).get('report')||saved.find(x=>x.status==='running')?.id;if(id)try{await open(id);}catch(e){notice(e.message);}})();
