const $=id=>document.getElementById(id);
const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=x=>x?new Date(x).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'Not checked';
const money=x=>'£'+Number(x||0).toLocaleString('en-GB',{maximumFractionDigits:0});
const fresh=(at,days)=>at && Date.parse(at)>Date.now()-days*86400000;
let catalog=[],visible=[],limit=50,scan=null,running=false,stopRequested=false,scope=null,connected=false,previewVersion=0;
const filters=()=>({mode:$('mode').value,service:$('service').value.trim().toLowerCase(),town:$('town').value.trim().toLowerCase(),budget:Number($('budget').value),jobValue:$('job-value').value});
async function api(route,body){const response=await fetch('/admin/emd-finder/api/'+route,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let data;try{data=await response.json();}catch{throw new Error('The server response could not be read. Reload to resume saved progress.');}if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
async function checkDomain(domain){let rdapStatus=0;try{const r=await fetch('https://rdap.nominet.uk/uk/domain/'+domain,{signal:AbortSignal.timeout(8000),credentials:'omit',redirect:'error',headers:{Accept:'application/rdap+json'}});const data=await r.json();if(r.status===404&&data.errorCode===404)rdapStatus=404;else if(r.status===200&&data.objectClassName==='domain'&&String(data.ldhName).toLowerCase()===domain)rdapStatus=200;}catch{}return api('availability',{domain,rdapStatus});}
function notice(text){$('notice').hidden=!text;$('notice').textContent=text||'';}
function registration(x){return !fresh(x.availabilityAt,1)?'Needs recheck':x.available===true?'Appears unregistered':x.available===false?'Registered':'Unknown';}
function render(){
  const f=filters(),q=$('search').value.toLowerCase(),view=$('view').value;
  visible=catalog.filter(x=>{
    const matching=(!f.service||x.service.includes(f.service))&&(!f.town||x.town===f.town);
    const value=f.jobValue!==''?Number(f.jobValue):x.jobValue;
    const mode=f.mode==='explore'?x.volume===null:x.volume!==null&&x.volume>=(f.mode==='value'?20:50)&&value>=(f.mode==='value'?1500:500);
    const status=view==='all'||(view==='active'?!['dismissed','purchased','partner-found'].includes(x.status):x.status===view);
    // Saved statuses and selected scans remain visible even after demand or assumptions change.
    return matching&&(scope?scope.includes(x.domain):view!=='active'||mode)&&status&&(!q||(x.domain+' '+x.service+' '+x.town).includes(q));
  }).sort((a,b)=>$('sort').value==='priority'?b.score-a.score:(b[$('sort').value]??-1)-(a[$('sort').value]??-1));
  $('total').textContent=visible.length.toLocaleString();$('available').textContent=visible.filter(x=>registration(x)==='Appears unregistered').length;$('promising').textContent=visible.filter(x=>x.evidence.label==='Promising').length;$('saved-count').textContent=catalog.filter(x=>x.status==='watchlist').length;
  $('rows').innerHTML=visible.slice(0,limit).map(x=>`<tr><td><strong>${escape(x.domain)}</strong><small>${escape(x.service+' '+x.town)}</small>${x.status!=='new'?`<small>${escape(x.status)}</small>`:''}</td><td><span class="number">${x.volume===null?'—':x.volume.toLocaleString()}</span><small>${x.volume===null?'Unreported':date(x.metricsAt)}${!fresh(x.metricsAt,90)?' · stale':''}</small></td><td>${money(x.jobValue)}<small>Assumed · ${x.commission}% = ${money(x.jobValue*x.commission/100)} / won job</small></td><td><span class="tag ${x.evidence.label==='Promising'?'good':x.evidence.label==='Defended'?'bad':'unknown'}">${escape(x.evidence.label)}</span><small>Keyword difficulty ${x.difficulty??'—'} / 100</small></td><td><span class="tag ${registration(x)==='Appears unregistered'?'good':'unknown'}">${registration(x)}</span><small>${date(x.availabilityAt)}</small></td><td><button data-domain="${escape(x.domain)}">Inspect ↗</button></td></tr>`).join('');
  $('more').hidden=visible.length<=limit;$('empty').hidden=visible.length>0;
}
async function load(){const data=await api('catalog');catalog=data.candidates;connected=data.connected;$('services').innerHTML=data.services.map(x=>`<option value="${escape(x)}"></option>`).join('');$('towns').innerHTML=data.towns.map(x=>`<option value="${escape(x)}"></option>`).join('');const selected=$('saved-scan').value;$('saved-scan').innerHTML='<option value="">All research / saved scans…</option>'+data.history.map(x=>`<option value="${escape(x.id)}">${date(x.created_at)} · ${escape(x.status)} · ${x.id.slice(0,6)}</option>`).join('');$('saved-scan').value=selected;render();return data;}
async function preview(){const version=++previewVersion;try{const p=await api('preview',filters());if(version!==previewVersion)return;$('preview').textContent=`${p.candidates} candidates · ${p.metricLookups} new metric lookups · estimated up to $${p.estimate.toFixed(3)} before cache savings. Your cap: $${p.filters.budget.toFixed(2)}.`;$('scan-button').disabled=running||!connected||!p.candidates;if(!connected)$('preview').textContent='DataForSEO is not connected. Saved research is still available.';}catch(e){if(version!==previewVersion)return;$('preview').textContent=e.message;$('scan-button').disabled=true;}}
function progress(){if(!scan)return;$('scan-progress').hidden=false;const phases={metrics:'Checking keyword metrics',availability:'Checking domain registration',serps:'Checking local Google competition',links:'Comparing competitor links',done:'Scan complete'};$('phase').textContent=scan.status==='stopped'?'Scan stopped':phases[scan.phase]||scan.phase;$('spend').textContent=`Reported spend $${scan.actual.toFixed(5)} · counted against budget $${scan.committed.toFixed(5)} / $${scan.budget.toFixed(2)} · ${scan.shortlist?.length||0} shortlisted`;$('scan-warnings').textContent=(scan.warnings||[]).join('\n')+(scan.ledger?.some(x=>x.status==='uncertain')?'\nAn interrupted or failed lookup has an uncertain charge; its reservation is still counted.':'');$('resume').hidden=running||scan.status!=='running';$('stop').hidden=scan.status!=='running';}
async function run(){if(running||!scan)return;running=true;stopRequested=false;$('scan-button').disabled=true;const controls=['mode','service','town','budget','job-value','saved-scan'];controls.forEach(id=>$(id).disabled=true);notice('');try{while(scan.status==='running'&&!stopRequested){progress();if(scan.registrationQueue?.length){for(const domain of scan.registrationQueue){if(stopRequested)break;await checkDomain(domain);await new Promise(resolve=>setTimeout(resolve,500));}if(stopRequested)break;}scan=await api('advance',{id:scan.id});progress();}if(stopRequested&&scan.status==='running'){await api('stop',{id:scan.id});scan=await api('scan?id='+scan.id);}await load();scope=scan.domains;render();}catch(e){notice(e.message+' Progress is saved. Use Resume scan to continue.');}finally{running=false;controls.forEach(id=>$(id).disabled=false);progress();await preview();}}
$('finder-form').addEventListener('submit',async event=>{event.preventDefault();if(running)return;$('scan-button').disabled=true;try{scan=await api('start',filters());scope=scan.domains;await run();}catch(e){notice(e.message);await preview();}});
$('resume').addEventListener('click',()=>run());$('stop').addEventListener('click',async()=>{stopRequested=true;if(!running&&scan){try{await api('stop',{id:scan.id});scan=await api('scan?id='+scan.id);progress();await preview();}catch(e){notice(e.message);}}});
let timer;for(const id of ['mode','service','town','budget','job-value'])$(id).addEventListener('input',()=>{scope=null;$('saved-scan').value='';limit=50;render();clearTimeout(timer);timer=setTimeout(preview,250);});
for(const id of ['search','view','sort'])$(id).addEventListener('input',()=>{limit=50;render();});
$('more').addEventListener('click',()=>{limit+=50;render();});
$('saved-scan').addEventListener('change',async()=>{try{if(!$('saved-scan').value){scope=null;render();return;}scan=await api('scan?id='+$('saved-scan').value);scope=scan.domains;for(const id of ['service','town'])$(id).value=scan.filters[id];$('mode').value=scan.filters.mode;progress();render();}catch(e){notice(e.message);}});
function inspect(domain){
  const x=catalog.find(c=>c.domain===domain);if(!x)return;
  const s=x.serp;$('detail-content').innerHTML=`<h2>${escape(x.domain)}</h2><p>${escape(x.service+' '+x.town)} · <strong>${escape(x.evidence.label)}</strong></p><p>${escape(x.evidence.reason)}</p>
  <div class="facts"><div><small>UK search demand</small>${x.volume??'Unreported'} / month<p>Retrieved ${date(x.metricsAt)}</p></div><div><small>SEO difficulty / paid CPC</small>${x.difficulty??'—'} / 100 · $${x.cpc??'—'}<p>CPC is an advertising metric.</p></div><div><small>Domain registration</small><span id="domain-status">${registration(x)}</span><p id="domain-date">${date(x.availabilityAt)}</p><button id="recheck-domain">Recheck availability · free</button></div></div>
  <h3>Commission scenario</h3><p>Enter assumptions for one month. Enquiries and conversion rates are hypothetical, not forecasts derived from search volume. Job value should mean one completed job; confirm a realistic figure with a partner.</p>
  <form id="notes-form"><div class="calculator"><label>Job value (£)<input id="edit-job" type="number" min="0" max="1000000" required value="${x.jobValue||0}"/></label><label>Commission (%)<input id="edit-commission" type="number" min="0" max="100" step="0.1" required value="${x.commission}"/></label><label>Enquiries / month<input id="enquiries" type="number" min="0" max="100000" value="10"/></label><label>Enquiries becoming jobs (%)<input id="close-rate" type="number" min="0" max="100" value="20"/></label></div><p class="scenario" id="scenario" aria-live="polite"></p>
  <div class="notes-grid"><label>Opportunity status<select id="edit-status">${['new','watchlist','dismissed','purchased','partner-found'].map(v=>`<option ${x.status===v?'selected':''} value="${v}">${v.replaceAll('-',' ')}</option>`).join('')}</select></label><label>Partner / research notes<textarea id="edit-notes" rows="3" maxlength="2000">${escape(x.notes||'')}</textarea></label></div><button class="primary" type="submit">Save opportunity</button><span id="saved-note" role="status" class="hint"></span></form>
  <h3>Local Google evidence</h3>${s?`<p>${escape(s.location)} · ${date(s.at)}${!fresh(s.at,30)?' · stale':''}. ${s.localPack?'Google Maps appears in these results and may reduce organic clicks.':''}</p><ol class="competitors">${s.items.map(c=>`<li value="${c.position}"><a href="${escape(c.url)}" target="_blank" rel="noopener noreferrer">${escape(c.title)}</a><small>${escape(c.domain)} · ${c.isDirectory?'Directory':`Domain referring domains: ${c.referringDomains??'unverified'} · ranking-page referring domains: ${c.pageReferringDomains??'unverified'}`} · links ${date(c.linksAt)}</small></li>`).join('')}</ol>`:'<p>No current local search snapshot. Run a scan to investigate shortlisted domains.</p>'}
  ${x.history?.median!==null&&x.history?.median!==undefined?`<details><summary>Archived competition data</summary><p>National search check from ${date(x.history.at)}: median ${x.history.median} referring domains, approximately ${Math.round(x.history.directories*100)}% directory results. This dated national check is not used to verify today’s local competition.</p></details>`:''}
  <p>Recheck with your registrar before purchasing. Inspect the businesses above and confirm a partner will accept leads at the assumed commission.</p>`;
  function calculate(){const v=Number($('edit-job').value),c=Number($('edit-commission').value),e=Number($('enquiries').value),r=Number($('close-rate').value);$('scenario').textContent=[v,c,e,r].some(x=>!Number.isFinite(x)||x<0)||c>100||r>100?'Enter valid assumptions.':`${e} enquiries × ${r}% close rate = ${Number((e*r/100).toFixed(2))} won jobs. At ${money(v*c/100)} commission per job: ${money(e*r/100*v*c/100)} gross commission / month, before costs.`;}
  for(const id of ['edit-job','edit-commission','enquiries','close-rate'])$(id).addEventListener('input',calculate);calculate();
  $('notes-form').addEventListener('submit',async event=>{event.preventDefault();try{await api('watch',{domain,status:$('edit-status').value,jobValue:Number($('edit-job').value),commission:Number($('edit-commission').value),notes:$('edit-notes').value});$('saved-note').textContent=' Saved';await load();}catch(e){$('saved-note').textContent=' '+e.message;}});
  $('recheck-domain').addEventListener('click',async()=>{const button=$('recheck-domain');button.disabled=true;try{const a=await checkDomain(domain);Object.assign(x,a);$('domain-status').textContent=registration(x);$('domain-date').textContent=date(a.availabilityAt);render();}catch(e){$('domain-status').textContent=e.message;}finally{button.disabled=false;}});
  if(!$('detail').open)$('detail').showModal();
}
$('rows').addEventListener('click',e=>{const button=e.target.closest('[data-domain]');if(button)inspect(button.dataset.domain);});$('close-detail').addEventListener('click',()=>$('detail').close());
$('export').addEventListener('click',()=>{const cell=value=>'"'+String(value??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const rows=[['Domain','Keyword','UK searches/month','Metrics retrieved','Estimated job value GBP','Commission percent','Competition','Registration','Registration checked','Status','Notes'],...visible.map(x=>[x.domain,x.service+' '+x.town,x.volume,x.metricsAt,x.jobValue,x.commission,x.evidence.label,registration(x),x.availabilityAt,x.status,x.notes])];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='nc-digital-emd-shortlist.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
(async()=>{try{const data=await load();const active=data.history.find(x=>x.status==='running');if(active){scan=await api('scan?id='+active.id);progress();notice('A saved scan is paused. Resume it to continue within its original budget.');}await preview();}catch(e){notice(e.message);$('preview').textContent='Saved research could not be loaded.';}})();
