import { esc,date,groups,secs,link,documentHtml,reviewEmailCopy } from '../lib/audit-report-view.js';
import { auditProgress } from '../lib/audit-progress.js';
const $=id=>document.getElementById(id);
let report=null,running=false,stopRequested=false,dirty=false;
async function api(route,body){const r=await fetch('/admin/website-audit/api/'+route,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let data;try{data=await r.json();}catch{throw new Error('The server response could not be read. Your saved audit can be reopened.');}if(!r.ok)throw new Error(data.error||'Audit request failed.');return data;}
function notice(text){$('notice').hidden=!text;$('notice').textContent=text||'';}
async function history(){const data=await api('history');const selected=report?.id||$('history').value;$('history').innerHTML='<option value="">Choose a report…</option>'+data.reports.map(r=>`<option value="${esc(r.id)}">${esc(r.client)} · ${date(r.created_at)} · ${esc(r.status)}</option>`).join('');$('history').value=selected;return data.reports;}
function progress(){if(!report)return;const pct=auditProgress(report);$('progress-fill').style.width=pct+'%';$('progress-pct').textContent=pct+'%';$('progress-bar').setAttribute('aria-valuenow',String(pct));$('progress').hidden=report.status!=='running';$('phase').textContent=({robots:'Checking crawl rules',pages:'Checking website pages',links:'Checking internal link destinations',https:'Checking the secure (HTTPS) redirect',sitemap:'Looking for an XML sitemap','speed-mobile':'Measuring mobile speed with Google (can take up to a minute)','speed-desktop':'Measuring desktop speed with Google',keywords:'Looking up local search demand',rankings:`Checking Google rankings in ${report.local?.townLabel||'the area'}`,done:'Audit complete'})[report.phase];$('progress-copy').textContent=`${report.pages.length} pages visited · ${report.linkChecks.length} extra links checked · ${report.skipped.length} pages excluded. You can close this page and resume later.`;$('resume').hidden=running||report.status!=='running';}
// ---- Nathan only: technical detail, uncertain items and manual checks. Never printed or downloaded ----
function internalHtml(r){const m=r.speed?.mobile,l=r.local,platform=r.pages.find(p=>p.parsed?.platform)?.parsed.platform;
  const notes=[...r.warnings,...(m?.error?['Speed: '+m.error]:[]),...(r.speed?.desktop?.error?['Desktop speed: '+r.speed.desktop.error]:[]),...(l?.error?['Local search: '+l.error]:[]),...(l?.warning?['Local search: '+l.warning]:[])];
  const hidden=groups(r.findings.filter(f=>f.internal)),shown=r.findings.filter(f=>!f.internal);
  const f=m?.field||{},row=(label,field,lab,fmt,target)=>`<tr><td>${label}</td><td>${field?esc(fmt(field.p75))+` <small>${esc(field.category.toLowerCase().replace('_',' '))}</small>`:'Not enough data'}</td><td>${lab!=null?esc(fmt(lab)):'—'}</td><td>${target}</td></tr>`;
  return `<div class="internal-doc">
  ${notes.length?`<h3>Things to know</h3>${notes.map(n=>`<p class="doc-warning">${esc(n)}</p>`).join('')}`:''}
  ${platform?`<p class="doc-section-copy"><strong>Platform:</strong> ${esc(platform)}</p>`:''}
  <h3>Worth checking yourself (${hidden.length})</h3><p class="doc-section-copy">Uncertain or technical items left out of the client report and score.</p>
  ${hidden.length?hidden.map(g=>`<section class="finding"><span class="badge review">${g.kind==='review'?'CHECK':'TECHNICAL'}</span><h4>${esc(g.title)}</h4><p>${esc(g.why)}</p><p><strong>Action:</strong> ${esc(g.fix)}</p>${g.items.map(i=>`<p>${link(i.page)}</p><div class="evidence">${esc(i.evidence)}</div>`).join('')}</section>`).join(''):'<p class="doc-section-copy">Nothing to check.</p>'}
  <h3>Evidence behind the client findings</h3>${shown.length?`<div class="doc-table-wrap"><table class="doc-table"><thead><tr><th>Finding</th><th>Page</th><th>Evidence</th></tr></thead><tbody>${shown.map(i=>`<tr><td>${esc(i.title)}</td><td>${i.page?link(i.page):'—'}</td><td class="pre">${esc(i.evidence)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="doc-section-copy">No client findings.</p>'}
  ${typeof m?.performance==='number'?`<h3>Speed detail (mobile)</h3><p class="doc-section-copy">Accessibility ${m.accessibility??'—'}/100 · Google SEO checks ${m.seo??'—'}/100 · Best practices ${m.bestPractices??'—'}/100</p><div class="doc-table-wrap"><table class="doc-table"><thead><tr><th>Measure</th><th>Real visitors</th><th>Lab test</th><th>Target</th></tr></thead><tbody>${row('Largest Contentful Paint',f.lcp,m.lab?.lcpMs,secs,'≤ 2.5s')}${row('Interaction to Next Paint',f.inp,null,v=>Math.round(v)+'ms','≤ 200ms')}${row('Cumulative Layout Shift',f.cls,m.lab?.cls,v=>String(Math.round(v*100)/100),'≤ 0.1')}</tbody></table></div>${m.opportunities?.length?`<ul class="manual-list">${m.opportunities.map(o=>`<li>${esc(o.title)}${o.savingsMs>=100?` (about ${secs(o.savingsMs)})`:''}</li>`).join('')}</ul>`:''}`:''}
  <h3>Check by hand before the meeting</h3><ul class="manual-list"><li>Open the website on a phone: readable text, working menu, nothing spilling off the screen.</li><li>Is the main service, area, proof of quality and next step clear straight away?</li><li>Send a test enquiry and check the phone and booking links work.</li><li>Look at image quality, real project photos and reviews.</li>${typeof m?.performance==='number'?'':`<li>Run <a href="https://pagespeed.web.dev/analysis?url=${encodeURIComponent(r.finalUrl||r.url)}" target="_blank" rel="noopener noreferrer">PageSpeed Insights</a> manually: speed was not measured.</li>`}</ul>
  <h3>Pages and links checked</h3><div class="doc-table-wrap"><table class="doc-table"><thead><tr><th>Address</th><th>Result</th><th>Coverage</th></tr></thead><tbody>${r.pages.map(p=>`<tr><td>${link(p.requestedUrl||p.url)}${p.redirects?.length?`<small>Redirected to ${esc(p.url)}</small>`:''}</td><td>${p.status?'HTTP '+p.status:'Not checked'}</td><td>${p.parsed?`${p.parsed.wordCount} words · ${p.parsed.images} images`:esc(p.error||'No HTML analysis')}</td></tr>`).join('')}${r.linkChecks.map(k=>`<tr><td>${esc(k.url)}</td><td>${k.status?'HTTP '+k.status:'Unknown'}</td><td>${esc(k.error||'Link destination only')}</td></tr>`).join('')}${r.skipped.map(p=>`<tr><td>${esc(p.url)}</td><td>Excluded</td><td>${esc(p.reason)}</td></tr>`).join('')}</tbody></table></div>
  <p class="doc-section-copy">${r.discovered.length} internal pages discovered. Checks read the HTML without running JavaScript; only HTTP 404/410 counts as a broken page.</p></div>`;
}
function render(){if(!report)return;$('empty').hidden=true;$('results').hidden=false;$('report-title').textContent=report.client;$('report-spend').hidden=!report.local;if(report.local)$('report-spend').textContent=`DataForSEO spend for local rankings: $${Number(report.local.cost||0).toFixed(3)} (not shown in the client report)`;$('report-document').innerHTML=documentHtml(report,{portfolio});$('internal-body').innerHTML=internalHtml(report);renderShare();renderEmails();$('rerun').disabled=running||report.status==='running';$('internal-count').textContent=report.findings.filter(f=>f.internal).length;if(!dirty){$('report-client').value=report.client;$('summary').value=report.summary;$('notes').value=report.notes;$('offer').value=report.offer||'auto';}progress();}
async function run(){if(running||!report)return;running=true;stopRequested=false;$('audit-fields').disabled=true;$('open-report').disabled=true;notice('');try{while(report.status==='running'&&!stopRequested){progress();report=await api('advance',{id:report.id});render();}if(stopRequested&&report.status==='running')report=await api('stop',{id:report.id});await history();render();}catch(e){notice(e.message+' Use Resume audit to continue saved progress.');}finally{running=false;$('audit-fields').disabled=false;$('open-report').disabled=false;progress();$('rerun').disabled=report?.status==='running';}}
$('audit-form').addEventListener('submit',async e=>{e.preventDefault();if(running)return;$('start').disabled=true;try{dirty=false;report=await api('start',{url:$('website').value,client:$('client').value,service:$('service').value,town:$('town').value,maxPages:Number($('page-limit').value),refresh:$('refresh').checked});render();window.history.replaceState(null,'','?report='+report.id);await run();if(report.cached)notice('Opened the saved audit. Select “Run a fresh audit” to check the website again.');}catch(e){notice(e.message);}finally{$('start').disabled=false;}});
$('resume').addEventListener('click',run);$('stop').addEventListener('click',async()=>{stopRequested=true;if(!running&&report){try{report=await api('stop',{id:report.id});render();await history();}catch(e){notice(e.message);}}});
async function open(id){if(running)return;dirty=false;report=await api('report?id='+encodeURIComponent(id));window.history.replaceState(null,'','?report='+report.id);render();}
$('open-report').addEventListener('click',async()=>{if(!$('history').value)return;try{await open($('history').value);}catch(e){notice(e.message);}});
for(const id of ['report-client','summary','notes','offer'])$(id).addEventListener(id==='offer'?'change':'input',()=>{dirty=true;$('notes-status').textContent='Unsaved changes';});
const ago=x=>{const m=Math.round((Date.now()-new Date(x))/60000);return m<1?'just now':m<60?m+' min ago':m<1440?Math.round(m/60)+' hours ago':date(x);};
function renderShare(){const s=report?.share;$('share-panel').hidden=!s;$('share').textContent=s?'Client link ✓':'Create client link';if(!s)return;
  $('share-url').value=s.url;$('open-share').href=s.url+'?preview=1';
  $('share-stats').textContent=s.views?`Opened ${s.views} time${s.views===1?'':'s'} · last ${ago(s.lastViewedAt)}. Your own opens count too.`:`Created ${ago(s.createdAt)} · not opened yet.`;}
async function copyShare(){try{await navigator.clipboard.writeText($('share-url').value);$('copy-share').textContent='Copied ✓';setTimeout(()=>{$('copy-share').textContent='Copy link';},2000);}catch{$('share-url').select();}}
$('share').addEventListener('click',async()=>{if(!report)return;try{await saveNotes();report={...report,...await api('share',{id:report.id,enable:true})};render();$('share-panel').scrollIntoView({behavior:'smooth',block:'nearest'});await copyShare();}catch(e){notice(e.message);}});
$('copy-share').addEventListener('click',copyShare);
$('unshare').addEventListener('click',async()=>{if(!report)return;try{report={...report,...await api('share',{id:report.id,enable:false})};render();notice('The client link has been turned off. Creating a new link gives a different address.');}catch(e){notice(e.message);}});
// ---- Email the review from the CRM mailbox ----
let emailEdited=false,emailKey=null,portfolio=[];
fetch('/portfolio-index.json').then(r=>r.ok?r.json():[]).then(items=>{portfolio=items;if(report)render();}).catch(()=>{});
const emailCopy=()=>reviewEmailCopy(report,$('email-name').value,report.share?.url||'');
function renderEmails(){const sent=report?.emails||[];$('email-history').innerHTML=sent.length?'<p class="eyebrow">SENT</p>'+sent.slice().reverse().map(e=>`<p>Emailed to <strong>${esc(e.name?e.name+' · ':'')}${esc(e.to)}</strong> · ${date(e.at)} · <a href="/admin/crm/?ticket=${encodeURIComponent(e.ticketId)}">${esc(e.reference)} in the CRM →</a></p>`).join(''):'';}
$('email-open').addEventListener('click',async()=>{if(!report)return;try{await saveNotes();if(!report.share)report={...report,...await api('share',{id:report.id,enable:true})};render();
  $('email-panel').hidden=false;if(!emailEdited)$('email-message').value=emailCopy();emailKey=emailKey||crypto.randomUUID();$('email-status').textContent='';$('email-panel').scrollIntoView({behavior:'smooth',block:'nearest'});$('email-to').focus();}catch(e){notice(e.message);}});
$('email-close').addEventListener('click',()=>{$('email-panel').hidden=true;});
$('email-name').addEventListener('input',()=>{if(!emailEdited)$('email-message').value=emailCopy();});
$('email-message').addEventListener('input',()=>{emailEdited=true;});
$('email-rewrite').addEventListener('click',()=>{emailEdited=false;$('email-message').value=emailCopy();});
$('email-form').addEventListener('submit',async e=>{e.preventDefault();if(!report)return;$('email-send').disabled=true;$('email-status').textContent='Sending…';
  try{report={...report,...await api('email',{id:report.id,name:$('email-name').value,email:$('email-to').value,message:$('email-message').value,request_key:emailKey})};
    emailKey=null;emailEdited=false;$('email-status').textContent='Queued: it sends from your mailbox within a minute. The conversation is in the CRM.';render();}
  catch(err){$('email-status').textContent=err.message;}finally{$('email-send').disabled=false;}});
$('rerun').addEventListener('click',async()=>{if(!report||running)return;try{await saveNotes();report=await api('rerun',{id:report.id});render();
  notice(report.share?'Updating with fresh data. Your client link stays the same and keeps showing the previous version until this finishes.':'Updating with fresh data.');await run();if(report.status==='complete')notice('Report updated with fresh data'+(report.share?'. Your client link now shows the new version.':'.'));}catch(e){notice(e.message);}});
async function saveNotes(){if(!report||!dirty)return;await api('notes',{id:report.id,client:$('report-client').value,summary:$('summary').value,notes:$('notes').value,offer:$('offer').value});Object.assign(report,{client:$('report-client').value,summary:$('summary').value,notes:$('notes').value,offer:$('offer').value});dirty=false;$('notes-status').textContent='Saved';render();await history();}
$('notes-form').addEventListener('submit',async e=>{e.preventDefault();try{await saveNotes();}catch(e){$('notes-status').textContent=e.message;}});
$('print').addEventListener('click',async()=>{try{await saveNotes();await document.fonts.ready;document.title=report.client+' — Website audit — NC Digital';window.print();}catch(e){notice(e.message);}});
$('download').addEventListener('click',async()=>{try{await saveNotes();const sheets=await Promise.all([...document.querySelectorAll('link[rel="stylesheet"]')].map(async l=>{const response=await fetch(l.href);if(!response.ok)throw new Error('Report styles could not be loaded.');return response.text();}));const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(report.client)+' — NC Digital website audit</title><style>'+sheets.join('\n')+'\nbody{background:#fff;color:#302838;font-family:Arial,sans-serif}.document{max-width:1100px;margin:auto}</style></head><body>'+documentHtml(report,{portfolio})+'</body></html>';const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='nc-digital-website-audit-'+report.client.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){notice(e.message);}});
let townVersion=0;$('town').addEventListener('input',async()=>{const version=++townVersion,q=$('town').value;if(q.length<2)return;try{const r=await fetch('/admin/keyword-research/api/locations?q='+encodeURIComponent(q)).then(x=>x.json());if(version===townVersion)$('audit-towns').innerHTML=(r.locations||[]).map(x=>`<option value="${esc(x.name)}">${esc(x.type)}</option>`).join('');}catch{}});
(async()=>{try{const reports=await history();$('start').disabled=false;const id=new URLSearchParams(location.search).get('report')||reports.find(r=>r.status==='running')?.id;if(id)await open(id);}catch(e){notice(e.message);}})();
