const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=x=>new Date(x).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'});
let report=null,running=false,stopRequested=false,dirty=false;
async function api(route,body){const r=await fetch('/admin/website-audit/api/'+route,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let data;try{data=await r.json();}catch{throw new Error('The server response could not be read. Your saved audit can be reopened.');}if(!r.ok)throw new Error(data.error||'Audit request failed.');return data;}
function notice(text){$('notice').hidden=!text;$('notice').textContent=text||'';}
async function history(){const data=await api('history');const selected=report?.id||$('history').value;$('history').innerHTML='<option value="">Choose a report…</option>'+data.reports.map(r=>`<option value="${esc(r.id)}">${esc(r.client)} · ${date(r.created_at)} · ${esc(r.status)}</option>`).join('');$('history').value=selected;return data.reports;}
function progress(){if(!report)return;$('progress').hidden=report.status!=='running';$('phase').textContent=({robots:'Checking crawl rules',pages:'Checking website pages',links:'Checking internal link destinations',done:'Audit complete'})[report.phase];$('progress-copy').textContent=`${report.pages.length} pages visited · ${report.linkChecks.length} extra links checked · ${report.skipped.length} pages excluded. You can close this page and resume later.`;$('resume').hidden=running||report.status!=='running';}
function groups(findings){const map=new Map();for(const f of findings){const key=f.title+'|'+f.kind;const group=map.get(key)||{...f,items:[]};group.items.push(f);map.set(key,group);}return [...map.values()];}
function documentHtml(r){const scanned=[...new Map(r.pages.filter(p=>p.parsed).map(p=>[p.url,p])).values()],all=groups(r.findings),high=all.filter(f=>f.priority==='high').length,confirmed=all.filter(f=>f.kind==='confirmed').length,review=all.filter(f=>f.kind==='review').length;
  const summary=r.summary||`This report reviews ${scanned.length} public HTML page${scanned.length===1?'':'s'} and ${r.linkChecks.length} additional internal link destinations on ${new URL(r.url).hostname}. It highlights practical improvements and records the evidence behind each recommendation.`;
  return `<article class="document"><div class="doc-top"><div class="doc-brand">NC <span>Digital</span></div><small>WEBSITE AUDIT & IMPROVEMENT PLAN<br/>Prepared ${date(r.createdAt)}</small></div><p class="eyebrow">PREPARED FOR ${esc(r.client).toUpperCase()}</p><h2>Website review</h2><p class="doc-meta"><a href="${esc(r.finalUrl||r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.finalUrl||r.url)}</a><br/>${r.status==='complete'?'Completed sample audit':r.status==='stopped'?'Partial audit · stopped':'Partial audit · in progress'}</p><p class="doc-intro">${esc(summary)}</p>
  <div class="doc-stats"><div class="doc-stat"><strong>${scanned.length}</strong><span>HTML pages checked</span></div><div class="doc-stat"><strong>${high}</strong><span>high-priority finding types</span></div><div class="doc-stat"><strong>${confirmed}</strong><span>confirmed finding types</span></div><div class="doc-stat"><strong>${review}</strong><span>finding types to review</span></div></div>
  ${r.warnings.map(w=>`<p class="doc-warning">${esc(w)}</p>`).join('')}${r.status!=='complete'?'<p class="doc-warning">This is a partial report. Outstanding checks have not been treated as passes.</p>':''}
  <h3>Recommended priorities</h3><p class="doc-section-copy">Findings are grouped by issue. “Confirmed” describes an observation in the downloaded page or HTTP response. “Review” needs context or a browser check before changes are agreed.</p>
  ${all.length?all.map(g=>`<section class="finding"><span class="badge ${g.kind==='review'?'review':g.priority}">${esc(g.priority.toUpperCase())} · ${g.kind==='review'?'REVIEW NEEDED':'CONFIRMED'}</span><h4>${esc(g.title)}</h4><p>${esc(g.why)}</p><p><strong>Suggested action:</strong> ${esc(g.fix)}</p>${g.items.map(f=>`<p><a href="${esc(f.page)}" target="_blank" rel="noopener noreferrer">${esc(f.page)}</a></p><div class="evidence">${esc(f.evidence)}</div>`).join('')}</section>`).join(''):`<p class="doc-section-copy">${scanned.length?'No issues were detected by these automated checks. Complete the visual and enquiry checks below before drawing a wider conclusion.':'No page-level findings are available because no HTML pages could be assessed.'}</p>`}
  <h3>Visual & enquiry checks</h3><p class="doc-section-copy">These checks need a person or a rendered browser test. They have not been marked as completed by this report.</p><ul class="manual-list"><li>Open the website on a phone: check readable text, navigation, layout overflow and tap targets.</li><li>Check that the main service, location, credibility and next step are clear without searching.</li><li>Test the enquiry form and confirm delivery with the business; check phone and booking links.</li><li>Review image quality, genuine project examples, testimonials and relevance to the target customer.</li><li>Measure loading performance using <a href="https://pagespeed.web.dev/analysis?url=${encodeURIComponent(r.finalUrl||r.url)}" target="_blank" rel="noopener noreferrer">PageSpeed Insights</a>. No speed score or Core Web Vitals assessment is included here.</li></ul>
  ${r.notes?`<h3>Proposed next steps</h3><div class="doc-notes">${esc(r.notes)}</div>`:''}
  <h3>Pages & links checked</h3><div class="doc-table-wrap"><table class="doc-table"><thead><tr><th>Address</th><th>Result</th><th>Coverage</th></tr></thead><tbody>${r.pages.map(p=>`<tr><td><a href="${esc(p.requestedUrl||p.url)}" target="_blank" rel="noopener noreferrer">${esc(p.requestedUrl||p.url)}</a>${p.redirects?.length?`<small>Redirected to ${esc(p.url)}</small>`:''}</td><td>${p.status?'HTTP '+p.status:'Not checked'}</td><td>${p.parsed?`${p.parsed.wordCount} words in HTML · ${p.parsed.images} images`:`${esc(p.error||'No HTML analysis')}`}</td></tr>`).join('')}${r.linkChecks.map(l=>`<tr><td>${esc(l.url)}</td><td>${l.status?'HTTP '+l.status:'Unknown'}</td><td>${esc(l.error||'Link destination only')}</td></tr>`).join('')}${r.skipped.map(p=>`<tr><td>${esc(p.url)}</td><td>Excluded</td><td>${esc(p.reason)}</td></tr>`).join('')}</tbody></table></div>
  <h3>Scope & interpretation</h3><div class="doc-limits"><ul><li>This is a sample of up to ${r.maxPages} pages and 20 further internal links, not an exhaustive website audit. ${r.discovered.length} eligible internal page addresses were discovered.</li><li>Checks inspect public HTML and HTTP responses. JavaScript is not executed, so content inserted by scripts may not be visible. Mobile layout, form delivery, accessibility compliance, rankings and speed require further testing.</li><li>Missing descriptions, headings or metadata do not prove lost rankings or revenue. Indexing directives and canonical choices may be intentional. A missing alt attribute is distinct from an empty attribute used for a decorative image.</li><li>Only HTTP 404/410 responses are treated as missing destinations. Blocking, timeouts and server failures are recorded separately. Crawl exclusions are respected; forms are never submitted.</li><li>Evidence reflects the website at the time of the audit. No DataForSEO credits were used. This report contains no invented traffic forecasts or revenue-loss estimates.</li></ul></div><footer class="doc-footer"><span>NC Digital · Website design & marketing</span><a href="https://nc-digital.co.uk">nc-digital.co.uk</a></footer></article>`;
}
function render(){if(!report)return;$('empty').hidden=true;$('results').hidden=false;$('report-title').textContent=report.client;$('report-document').innerHTML=documentHtml(report);if(!dirty){$('report-client').value=report.client;$('summary').value=report.summary;$('notes').value=report.notes;}progress();}
async function run(){if(running||!report)return;running=true;stopRequested=false;$('audit-fields').disabled=true;$('open-report').disabled=true;notice('');try{while(report.status==='running'&&!stopRequested){progress();report=await api('advance',{id:report.id});render();}if(stopRequested&&report.status==='running')report=await api('stop',{id:report.id});await history();render();}catch(e){notice(e.message+' Use Resume audit to continue saved progress.');}finally{running=false;$('audit-fields').disabled=false;$('open-report').disabled=false;progress();}}
$('audit-form').addEventListener('submit',async e=>{e.preventDefault();if(running)return;$('start').disabled=true;try{dirty=false;report=await api('start',{url:$('website').value,client:$('client').value,maxPages:Number($('page-limit').value),refresh:$('refresh').checked});render();window.history.replaceState(null,'','?report='+report.id);await run();if(report.cached)notice('Opened the saved audit. Select “Run a fresh audit” to check the website again.');}catch(e){notice(e.message);}finally{$('start').disabled=false;}});
$('resume').addEventListener('click',run);$('stop').addEventListener('click',async()=>{stopRequested=true;if(!running&&report){try{report=await api('stop',{id:report.id});render();await history();}catch(e){notice(e.message);}}});
async function open(id){if(running)return;dirty=false;report=await api('report?id='+encodeURIComponent(id));window.history.replaceState(null,'','?report='+report.id);render();}
$('open-report').addEventListener('click',async()=>{if(!$('history').value)return;try{await open($('history').value);}catch(e){notice(e.message);}});
for(const id of ['report-client','summary','notes'])$(id).addEventListener('input',()=>{dirty=true;$('notes-status').textContent='Unsaved changes';});
async function saveNotes(){if(!report||!dirty)return;await api('notes',{id:report.id,client:$('report-client').value,summary:$('summary').value,notes:$('notes').value});Object.assign(report,{client:$('report-client').value,summary:$('summary').value,notes:$('notes').value});dirty=false;$('notes-status').textContent='Saved';render();await history();}
$('notes-form').addEventListener('submit',async e=>{e.preventDefault();try{await saveNotes();}catch(e){$('notes-status').textContent=e.message;}});
$('print').addEventListener('click',async()=>{try{await saveNotes();await document.fonts.ready;document.title=report.client+' — Website audit — NC Digital';window.print();}catch(e){notice(e.message);}});
$('download').addEventListener('click',async()=>{try{await saveNotes();const sheets=await Promise.all([...document.querySelectorAll('link[rel="stylesheet"]')].map(async l=>{const response=await fetch(l.href);if(!response.ok)throw new Error('Report styles could not be loaded.');return response.text();}));const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(report.client)+' — NC Digital website audit</title><style>'+sheets.join('\n')+'\nbody{background:#fff;color:#302838;font-family:Arial,sans-serif}.document{max-width:1100px;margin:auto}</style></head><body>'+documentHtml(report)+'</body></html>';const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='nc-digital-website-audit-'+report.client.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){notice(e.message);}});
(async()=>{try{const reports=await history();$('start').disabled=false;const id=new URLSearchParams(location.search).get('report')||reports.find(r=>r.status==='running')?.id;if(id)await open(id);}catch(e){notice(e.message);}})();
