import {test,expect} from '@playwright/test';
const site='sc-domain:nc-digital.co.uk',url='https://nc-digital.co.uk/roofing/';
const metric={clicks:5,impressions:500,ctr:.01,position:8};
const op={type:'striking-distance',page:url,query:'roofing cardiff',current:metric,previous:null,score:70,confidence:'More evidence',reason:'500 impressions and average position 8.',actions:['Review the page intent.','Improve relevant service details.']};
const report={input:{country:'gbr',device:'all'},periods:{current:{startDate:'2026-08-10',endDate:'2026-09-06'},previous:{startDate:'2026-07-13',endDate:'2026-08-09'}},overview:{current:metric,previous:metric},opportunities:[op],pages:[{page:url,current:metric,previous:metric,score:70,types:['striking-distance'],queries:['roofing cardiff'],opportunities:[0]}],trend:[],coverage:{currentPairs:1,previousPairs:1,currentPages:1,previousPages:1},warnings:[],missingCurrent:[]};
async function setup(page,{expired=false}={}){let task={page:url,status:'to-do',notes:''};await page.route('**/admin/seo-quick-wins/api/**',async route=>{const path=new URL(route.request().url()).pathname.split('/').at(-1);let data;if(path==='sites')data=expired?{connected:false,sites:[],message:'Google requires a fresh Search Console sign-in.'}:{connected:true,sites:[{site}]};else if(path==='history')data={reports:[]};else if(path==='tasks')data={tasks:[task]};else if(path==='task'){task={...task,...route.request().postDataJSON()};data={ok:true};}else data={id:'report-1',site,status:path==='start'?'running':'complete',stage:7,counts:{currentPairs:1},report:path==='start'?null:report};await route.fulfill({json:data});});}
test('research shows evidence, handles unknown previous data and saves the page work item',async({page})=>{await setup(page);await page.goto('/admin/seo-quick-wins/');await page.getByRole('button',{name:'Find quick wins ↗'}).click();await expect(page.locator('#rows')).toContainText('roofing cardiff');await expect(page.locator('#rows')).toContainText('Previous: —');await page.getByRole('button',{name:'Inspect ↗'}).click();await expect(page.locator('#detail')).toContainText('500 impressions');await page.getByRole('button',{name:'Open page work plan'}).click();await page.locator('[data-task-status]').selectOption('in-progress');await page.locator('[data-task-notes]').fill('Added useful project examples.');await page.getByRole('button',{name:'Save work item'}).click();await expect(page.locator('.save-state')).toHaveText('Saved');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export opportunities'}).click();expect((await download).suggestedFilename()).toBe('nc-digital-seo-quick-wins.csv');});
test('expired connection gives a clear next step and prevents new research',async({page})=>{await setup(page,{expired:true});await page.goto('/admin/seo-quick-wins/');await expect(page.locator('#connection')).toContainText('fresh Search Console sign-in');await expect(page.locator('#start')).toBeDisabled();});
test('mobile layout and print work plan are usable',async({page})=>{await setup(page);await page.setViewportSize({width:390,height:844});await page.goto('/admin/seo-quick-wins/?report=report-1');await expect(page.locator('#rows')).toContainText('roofing cardiff');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.tmp/wins-mobile.png',fullPage:true});await page.emulateMedia({media:'print'});await expect(page.locator('#pages-panel')).toBeVisible();await expect(page.locator('header')).toBeHidden();await page.pdf({path:'.tmp/wins-test.pdf',format:'A4',printBackground:true});});
