import { test,expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
const report={id:'audit-1',url:'https://example.co.uk/',client:'Example Roofing',createdAt:'2026-09-09T10:00:00Z',status:'complete',phase:'done',notes:'',summary:'',maxPages:5,finalUrl:'https://example.co.uk/',warnings:[],skipped:[],discovered:['https://example.co.uk/'],linkChecks:[],pages:[{url:'https://example.co.uk/',status:200,parsed:{wordCount:300,images:4}}],score:{overall:62,grade:'Needs work',categories:[{key:'seo',label:'Search visibility',score:70,measured:true},{key:'speed',label:'Mobile & speed',score:41,measured:true},{key:'trust',label:'Trust & accessibility',score:84,measured:true},{key:'enquiry',label:'Enquiries & local',score:60,measured:true}]},speed:{mobile:{performance:38,accessibility:72,seo:90,bestPractices:80,lab:{lcpMs:6200,cls:0.31},field:{lcp:{p75:4800,category:'SLOW'},inp:null,cls:{p75:0.12,category:'AVERAGE'},originFallback:false},opportunities:[{title:'Serve images in next-gen formats',savingsMs:2600}]},desktop:{performance:81}},local:{service:'roofer',town:'cardiff',townLabel:'Cardiff',cost:0.034,keywords:[{keyword:'roofer cardiff',volume:880,cpc:4.1,checked:true,position:null,mapPackShown:true,inMapPack:false,mapPack:['Top Roofing Cardiff','Bay Roofers','Capital Roofing'],top3:[{position:1,domain:'checkatrade.com',title:'Roofers in Cardiff'},{position:2,domain:'toproofing.co.uk',title:'Top Roofing Cardiff'},{position:3,domain:'rival.co.uk',title:'Rival Roofing'}]},{keyword:'roofers in cardiff',volume:320,cpc:3.2,checked:true,position:14},{keyword:'roof repairs cardiff',volume:260,cpc:5.5,checked:true,position:null},{keyword:'local roofer cardiff',volume:30,cpc:null}]},findings:[{title:'Page language is not declared',priority:'medium',kind:'confirmed',internal:true,why:'Screen readers use it.',fix:'Set lang.',page:'https://example.co.uk/',evidence:'No lang attribute on <html>.'},{title:'Page title is missing',priority:'high',kind:'confirmed',why:'A clear title helps explain the page.',fix:'Write a relevant title.',page:'https://example.co.uk/',evidence:'No title found.'}]};
let rerun=0;async function mock(page){rerun=0;let saved={...report};await page.route('**/admin/website-audit/api/**',async route=>{const path=new URL(route.request().url()).pathname.split('/').at(-1);let result;if(path==='history')result={reports:[saved]};else if(path==='notes'){saved={...saved,...route.request().postDataJSON()};result={ok:true};}else if(path==='rerun'){rerun++;result={...saved,status:'running',phase:'robots'};}else if(path==='email'){const b=route.request().postDataJSON();saved={...saved,lastEmail:b,emails:[...(saved.emails||[]),{to:b.email,name:b.name,at:new Date().toISOString(),ticketId:'ticket-1',reference:'NC-ABCDEF0123456789'}]};result=saved;}else if(path==='share'){const on=route.request().postDataJSON().enable!==false;saved={...saved,share:on?{token:'AbCdEfGhIjKlMnOpQrStUv_-',url:'https://nc-digital.co.uk/report/AbCdEfGhIjKlMnOpQrStUv_-',createdAt:new Date().toISOString(),views:0,lastViewedAt:null}:null};result=saved;}else if(path==='start')result={...saved,status:'running',phase:'robots'};else result=saved;await route.fulfill({json:result});});}
test('audit completes and report notes persist before export',async({page})=>{await mock(page);await page.goto('/admin/website-audit/');await page.locator('#website').fill('example.co.uk');await page.getByRole('button',{name:'Audit website ↗'}).click();await expect(page.locator('.document')).toContainText('Page title is missing');await expect(page.locator('.document')).not.toContainText('Page language is not declared');await expect(page.locator('.document')).not.toContainText('HTTP');await expect(page.locator('.document')).not.toContainText('CONFIRMED');await expect(page.locator('#internal')).toContainText('1 items to check');await page.locator('#internal summary').click();await expect(page.locator('.internal-doc')).toContainText('Page language is not declared');await expect(page.locator('.internal-doc')).toContainText('No lang attribute');await expect(page.locator('.internal-doc')).toContainText('Serve images in next-gen formats');await expect(page.locator('.doc-score')).toContainText('Needs work');await expect(page.locator('.doc-local')).toContainText('Around 1,490 searches a month');await expect(page.locator('.doc-local')).toContainText('0 of 3');await expect(page.locator('.doc-local')).toContainText('is not shown');await expect(page.locator('#report-spend')).toContainText('$0.034');await expect(page.locator('.document')).toContainText('How fast the website loads');await expect(page.locator('.document')).not.toContainText('next-gen formats');await page.locator('#editor summary').click();await page.locator('#notes').fill('Improve the service pages and add a quote form.');await page.getByRole('button',{name:'Save report notes'}).click();await expect(page.locator('.doc-notes')).toContainText('Improve the service pages');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download report'}).click();expect((await download).suggestedFilename()).toContain('nc-digital-website-audit');});
test('untrusted text is escaped and print layout is suitable for a client',async({page})=>{await mock(page);await page.goto('/admin/website-audit/?report=audit-1');await expect(page.locator('.document')).toBeVisible();await page.locator('#editor summary').click();await page.locator('#summary').fill('<img src=x onerror=alert(1)>');await page.getByRole('button',{name:'Save report notes'}).click();await expect(page.locator('.doc-intro')).toContainText('<img');expect(await page.locator('.doc-intro img').count()).toBe(0);await page.emulateMedia({media:'print'});await expect(page.locator('.topbar')).toBeHidden();await expect(page.locator('#editor')).toBeHidden();await expect(page.locator('#internal')).toBeHidden();await expect(page.locator('.document')).toBeVisible();await page.pdf({path:'.tmp/audit-test-report.pdf',format:'A4',printBackground:true});});
test('mobile screen has no page overflow',async({page})=>{await mock(page);await page.setViewportSize({width:390,height:844});await page.goto('/admin/website-audit/?report=audit-1');await expect(page.locator('.document')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.tmp/audit-mobile.png',fullPage:true});await page.setViewportSize({width:1280,height:900});await page.locator('.doc-local').screenshot({path:'.tmp/audit-local-desktop.png'});await page.locator('.start').screenshot({path:'.tmp/audit-form-desktop.png'});});

test('client link can be created, copied and turned off',async({page,context})=>{await context.grantPermissions(['clipboard-read','clipboard-write']);await mock(page);await page.goto('/admin/website-audit/?report=audit-1');await expect(page.locator('#share-panel')).toBeHidden();await page.getByRole('button',{name:'Create client link'}).click();await expect(page.locator('#share-panel')).toBeVisible();await expect(page.locator('#share-url')).toHaveValue('https://nc-digital.co.uk/report/AbCdEfGhIjKlMnOpQrStUv_-');await expect(page.locator('#share-stats')).toContainText('not opened yet');await page.getByRole('button',{name:'Turn off link'}).click();await expect(page.locator('#share-panel')).toBeHidden();await expect(page.getByRole('button',{name:'Create client link'})).toBeVisible();});
test('public report page shows the client report with a call to action and no admin detail',async({page})=>{
  const view={client:'Example Roofing',createdAt:report.createdAt,url:report.url,finalUrl:report.finalUrl,status:'complete',summary:'',notes:'We would start with the service pages.',maxPages:5,pagesChecked:2,score:report.score,local:report.local,speed:{mobile:{performance:38,field:{lcp:{p75:4800}},lab:{lcpMs:6200}},desktop:{performance:81}},offerView:{type:'website',platform:'Wix'},findings:[{id:'title-1',title:'Page title is missing',why:'A clear title helps.',fix:'Write a relevant title.',page:'https://example.co.uk/',priority:'high',kind:'confirmed'}]};
  await page.route('**/report/AbCdEfGhIjKlMnOpQrStUv_-',route=>route.fulfill({contentType:'text/html',body:readFileSync('dist/report/index.html','utf8')}));
  await page.route('**/api/report/**',route=>route.fulfill({json:view}));
  let enquiry=null;await page.route('**/api/enquiries',route=>{enquiry=route.request().postDataJSON();route.fulfill({json:{success:true}});});
  await page.setViewportSize({width:390,height:844});await page.goto('/report/AbCdEfGhIjKlMnOpQrStUv_-');
  await expect(page.locator('.document')).toContainText('Page title is missing');await expect(page.locator('.doc-local')).toContainText('Roofer in Cardiff');await expect(page.locator('.doc-notes')).toContainText('service pages');
  await expect(page.locator('#cta')).toContainText('Want these fixed?');await expect(page.locator('#offer')).toContainText('A multi-page WordPress website');await expect(page.locator('#offer')).not.toContainText('£199');await expect(page.locator('#offer')).toContainText('currently built with Wix');await page.locator('.offer-jump').click();await expect(page.locator('#offer')).toBeInViewport();await page.evaluate(()=>scrollTo(0,0));
  await expect(page.locator('#offer a.offer-btn')).toHaveAttribute('href','#get-in-touch');await expect(page.locator('.pr-nav a.pr-btn-primary')).toHaveAttribute('href','#get-in-touch');
  const quote=page.locator('#quote-form');await expect(quote.locator('[name=company]')).toHaveValue('Example Roofing');await expect(quote.locator('[name=message]')).toHaveValue(/new multi-page WordPress website/);await expect(quote.locator('[name=message]')).toHaveValue(/roofer in Cardiff/);
  await quote.getByRole('button',{name:'Send to Nathan'}).click();await expect(page.locator('#quote-error')).toContainText('name');expect(enquiry).toBe(null);
  await quote.locator('[name=name]').fill('Gareth Evans');await quote.locator('[name=email]').fill('gareth@example.co.uk');await quote.locator('[name=phone]').fill('07700 900123');
  await quote.getByRole('button',{name:'Send to Nathan'}).click();await expect(page.locator('#quote-success')).toBeVisible();await expect(quote).toBeHidden();
  expect(enquiry).toMatchObject({name:'Gareth Evans',email:'gareth@example.co.uk',phone:'07700 900123',company:'Example Roofing',service:'Multi-page WordPress website',from_page:'/report/AbCdEfGhIjKlMnOpQrStUv_-',website_url:'https://example.co.uk/',lead_source:'Website review link',lead_temperature:'hot'});expect(enquiry.submission_key).toMatch(/^[0-9a-f-]{36}$/);
  await page.screenshot({path:'.tmp/public-report-form.png'});await page.evaluate(()=>scrollTo(0,0));await expect(page).toHaveTitle(/Example Roofing website review/);
  for(const hidden of ['#internal','#share-panel','#editor','.internal-doc'])expect(await page.locator(hidden).count()).toBe(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.tmp/public-report-mobile.png',fullPage:true});await page.setViewportSize({width:1366,height:900});await page.screenshot({path:'.tmp/public-report-desktop.png',fullPage:true});await page.emulateMedia({media:'print'});await expect(page.locator('.pr-nav')).toBeHidden();await expect(page.locator('#cta')).toBeHidden();await page.screenshot({path:'.tmp/public-report-print.png',fullPage:true});await page.emulateMedia({media:'screen'});
  await page.route('**/api/report/**',route=>route.fulfill({status:404,json:{error:'This report link is not available. Please contact NC Digital for an up-to-date copy.'}}));await page.reload();await expect(page.locator('#status')).toContainText('not available');await expect(page.locator('#cta')).toBeHidden();
});

test('the review can be emailed with written copy that includes the client link',async({page})=>{await mock(page);await page.goto('/admin/website-audit/?report=audit-1');
  await page.getByRole('button',{name:'Email to client'}).click();await expect(page.locator('#email-panel')).toBeVisible();
  const message=page.locator('#email-message');await expect(message).toHaveValue(/https:\/\/nc-digital\.co\.uk\/report\/AbCdEfGhIjKlMnOpQrStUv_-/);await expect(message).toHaveValue(/^Hi,/);
  await page.locator('#email-name').fill('Gareth Evans');await expect(message).toHaveValue(/^Hi Gareth,/);await expect(message).toHaveValue(/Cardiff/);
  await page.locator('#email-to').fill('gareth@example.co.uk');await page.locator('#email-panel').screenshot({path:'.tmp/email-panel.png'});await page.getByRole('button',{name:'Send email'}).click();
  await expect(page.locator('#email-status')).toContainText('Queued');await expect(page.locator('#email-history')).toContainText('gareth@example.co.uk');await expect(page.locator('#email-history a')).toHaveAttribute('href','/admin/crm/?ticket=ticket-1');
  await page.emulateMedia({media:'print'});await expect(page.locator('#email-panel')).toBeHidden();});

test('a saved report can be updated with fresh data in place',async({page})=>{await mock(page);await page.goto('/admin/website-audit/?report=audit-1');await expect(page.locator('.document')).toBeVisible();
  await page.getByRole('button',{name:'Update with fresh data'}).click();await expect(page.locator('#notice')).toContainText('Report updated with fresh data');expect(rerun).toBe(1);await expect(page.getByRole('button',{name:'Update with fresh data'})).toBeEnabled();});
test('a running audit shows how far through it is',async({page})=>{
  const running={...report,status:'running',phase:'pages',maxPages:5,queue:['https://example.co.uk/a'],pages:[report.pages[0],{url:'https://example.co.uk/b',status:200,parsed:{wordCount:10,images:0}}],linkChecks:[],skipped:[],local:null,score:null};
  await page.route('**/admin/website-audit/api/**',async route=>{const path=new URL(route.request().url()).pathname.split('/').at(-1);await route.fulfill({json:path==='history'?{reports:[running]}:running});});
  await page.goto('/admin/website-audit/?report=audit-1');await expect(page.locator('#progress')).toBeVisible();
  const pct=Number((await page.locator('#progress-pct').textContent()).replace('%',''));expect(pct).toBeGreaterThan(0);expect(pct).toBeLessThan(50);
  await expect(page.locator('#progress-bar')).toHaveAttribute('aria-valuenow',String(pct));await page.locator('#progress').screenshot({path:'.tmp/progress.png'});});

test('a shared SEO report shows the plain-English report with a questions form instead of a sales pitch',async({page})=>{
  const seo={type:'seo',notes:'Added a Cardiff solar page.',forms:null,report:{property:{name:'IR Energy'},input:{site:'sc-domain:ir-energy.co.uk'},periods:{current:{startDate:'2026-08-01',endDate:'2026-08-31'},previous:{startDate:'2026-07-01',endDate:'2026-07-31'},currentDays:31,previousDays:31},cards:[{key:'clicks',source:'gsc',type:'number',current:180,previous:120},{key:'position',source:'gsc',type:'position',current:14.2,previous:18.9}],data:{gscCurrentTrend:{rows:[{keys:['2026-08-02'],clicks:180}]},gscPreviousTrend:{rows:[{keys:['2026-07-02'],clicks:120}]}},client:{name:'IR Energy',brandTerms:[],enquiryEvents:[]},rankings:{current:[{keyword:'solar panels cardiff',position:8}],previous:{'solar panels cardiff':24},checkedAt:'2026-09-01T10:00:00Z',locationName:'Cardiff,Wales,United Kingdom'}}};
  await page.route('**/report/AbCdEfGhIjKlMnOpQrStUv_-',route=>route.fulfill({contentType:'text/html',body:readFileSync('dist/report/index.html','utf8')}));
  await page.route('**/api/report/**',route=>route.fulfill({json:seo}));
  await page.goto('/report/AbCdEfGhIjKlMnOpQrStUv_-');
  await expect(page).toHaveTitle(/IR Energy SEO report/);await expect(page.locator('.sr-doc')).toContainText('IR Energy SEO Report 01/08/2026 – 31/08/2026');await expect(page.locator('.sr-doc')).toContainText('Clicks from Google, month by month');
  await expect(page.locator('.sr-doc')).toContainText('▲ up 16 places');await expect(page.locator('.sr-doc')).toContainText('Added a Cardiff solar page.');
  await expect(page.locator('#cta-title')).toHaveText('Questions about your report?');await expect(page.locator('#cta-quote')).toBeHidden();await expect(page.locator('#quote-form [name=message]')).toHaveValue(/talk through my SEO report/);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
