import {test,expect} from '@playwright/test';
import {buildAnalyticsReport,reportPeriods} from '../src/lib/analytics-report.js';
const input={property:'properties/123',site:'sc-domain:nc-digital.co.uk',period:'6',country:'all'},state={input,property:{id:input.property,name:'NC Digital',timeZone:'Europe/London'},periods:reportPeriods(input,'Europe/London',new Date('2026-09-09T12:00Z')),warnings:[],stage:1,stages:['overview']};
const totals={rows:[{dimensions:{dateRange:'current'},metrics:{sessions:100,activeUsers:70,newUsers:40,screenPageViews:300,engagementRate:.65,keyEvents:0,sessionKeyEventRate:0,userEngagementDuration:3500}},{dimensions:{dateRange:'previous'},metrics:{sessions:80,activeUsers:50,newUsers:30,screenPageViews:250,engagementRate:.5,keyEvents:0,sessionKeyEventRate:0,userEngagementDuration:2500}}]};
const report=buildAnalyticsReport(state,{overview:totals,organic:totals,channels:{rows:[{dimensions:{dateRange:'current',sessionDefaultChannelGroup:'Organic Search'},metrics:{sessions:50,engagementRate:.5,keyEvents:0}}]},gscCurrentTotals:{rows:[{clicks:100,impressions:10000,ctr:.01,position:10}]},gscPreviousTotals:{rows:[{clicks:80,impressions:8000,ctr:.01,position:12}]}});
async function setup(page,{disabled=false}={}){const starts=[];let notes='';await page.route('**/admin/analytics-reports/api/**',async route=>{const kind=new URL(route.request().url()).pathname.split('/').at(-1);let data;if(kind==='connection')data=disabled?{connected:false,properties:[],sites:[],message:'Enable the Analytics Admin API in the Google Cloud project used by this connection, then retry.'}:{connected:true,properties:[{property:input.property,name:'NC Digital',account:'Agency'}],sites:[input.site]};else if(kind==='history')data={reports:[]};else if(kind==='notes'){notes=route.request().postDataJSON().notes;data={ok:true};}else{if(kind==='start')starts.push(route.request().postDataJSON());data={id:'report-1',title:'NC Digital',status:kind==='start'?'running':'complete',...state,report:kind==='start'?null:report,notes};}await route.fulfill({json:data});});return {starts,notes:()=>notes};}
test('six-month combined report has explanations, comparisons, saved commentary and CSV',async({page})=>{const mock=await setup(page);await page.goto('/admin/analytics-reports/');await page.locator('#period').selectOption('6');await page.getByRole('button',{name:'Create client report ↗'}).click();await expect(page.locator('#report')).toBeVisible();expect(mock.starts[0].period).toBe('6');expect(mock.starts[0].site).toBe(input.site);await expect(page.locator('#dates')).toContainText('184 days');await expect(page.locator('#dates')).toContainText('181 days');await expect(page.locator('#website-cards')).toContainText('+15.0 percentage points');await expect(page.locator('#search-cards')).toContainText('2.0 positions better');await page.locator('#website-cards details').first().locator('summary').click();await expect(page.locator('#website-cards')).toContainText('periods contain 184 and 181 days');await page.locator('#notes').fill('Improved service page content. Next: review enquiry tracking.');await page.getByRole('button',{name:'Save commentary'}).click();expect(mock.notes()).toContain('Next:');await expect(page.locator('#notes-status')).toHaveText('Saved');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export figures'}).click();expect((await download).suggestedFilename()).toBe('nc-digital-client-report.csv');});
test('custom dates are required and submitted; disabled API leaves an actionable setup message',async({page})=>{await setup(page,{disabled:true});await page.goto('/admin/analytics-reports/');await expect(page.locator('#connection')).toContainText('Enable the Analytics Admin API');await expect(page.locator('#start')).toBeDisabled();await page.locator('#period').selectOption('custom');await expect(page.locator('#custom-dates')).toBeVisible();await expect(page.locator('#start-date')).toHaveAttribute('required','');});
test('mobile layout has no page overflow and PDF includes explanations and saved notes',async({page})=>{await setup(page);await page.setViewportSize({width:390,height:844});await page.goto('/admin/analytics-reports/?report=report-1');await expect(page.locator('#report')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.tmp/analytics-mobile.png',fullPage:false});await page.locator('#notes').fill('Review form tracking next month.');await page.evaluate(()=>{window.print=()=>{};});await page.getByRole('button',{name:'Print / save PDF'}).click();await expect(page.locator('#notes-status')).toHaveText('Saved');await page.emulateMedia({media:'print'});await expect(page.locator('#print-notes')).toBeVisible();await expect(page.locator('#website-cards details').first()).toHaveAttribute('open','');await page.pdf({path:'.tmp/analytics-report-test.pdf',format:'A4',printBackground:true});await page.setViewportSize({width:1000,height:1200});await page.screenshot({path:'.tmp/analytics-print.png',fullPage:false});});

