import test from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import worker from '../../src/worker.js';
import {resolveAccessRole} from '../../src/lib/admin-access.js';
const pair=await generateKeyPair('RS256'),jwk={...await exportJWK(pair.publicKey),kid:'test-key',alg:'RS256',use:'sig'};
function setup(t){const env={ADMIN_AUTH_MODE:'access',ACCESS_TEAM_DOMAIN:`https://test-${crypto.randomUUID()}.cloudflareaccess.com`,ACCESS_AUD:'test-audience',ACCESS_NATHAN_EMAIL:'nathan@example.com',ACCESS_BEN_EMAIL:'ben@example.com',ADMIN_PASSWORD:'old-password',ASSETS:{fetch:async()=>new Response('private-page')}};
  t.mock.method(globalThis,'fetch',async(url,options)=>{assert.equal(String(url),env.ACCESS_TEAM_DOMAIN+'/cdn-cgi/access/certs');assert(!options.headers?.Authorization);return Response.json({keys:[jwk]});});return env;
}
async function token(env,claims={}){const now=Math.floor(Date.now()/1000);return new SignJWT({sub:'identity-1',email:env.ACCESS_NATHAN_EMAIL,iss:env.ACCESS_TEAM_DOMAIN,aud:env.ACCESS_AUD,iat:now,exp:now+3600,...claims}).setProtectedHeader({alg:'RS256',kid:'test-key'}).sign(pair.privateKey);}
function request(path,jwt){return new Request('https://nc-digital.co.uk'+path,{headers:{Authorization:'Basic '+btoa('nathan:old-password'),...(jwt?{'Cf-Access-Jwt-Assertion':jwt}:{})}});}
test('managed login verifies signatures and allows named users only',async t=>{const env=setup(t);assert.equal(await resolveAccessRole(request('/admin/crm/',await token(env)),env),'nathan');assert.equal(await resolveAccessRole(request('/admin/crm/',await token(env,{email:'outsider@example.com',role:'admin'})),env),null);});

test('CRM scoped managed login blocks password bypass on every hostname and preserves other admin tools',async t=>{const env=setup(t);env.ADMIN_AUTH_SCOPE='crm';assert.equal((await worker.fetch(request('/admin/jobs/'),env)).status,200);assert.equal((await worker.fetch(request('/admin/crm/'),env)).status,401);const direct=new Request('https://nc-digital.example.workers.dev/admin/crm/',{headers:{Authorization:'Basic '+btoa('nathan:old-password')}});assert.equal((await worker.fetch(direct,env)).status,401);assert.equal((await worker.fetch(request('/admin/crm/',await token(env)),env)).status,200);});
test('Ben retains jobs-only access with a valid managed identity',async t=>{const env=setup(t),jwt=await token(env,{email:env.ACCESS_BEN_EMAIL});assert.equal(await resolveAccessRole(request('/admin/jobs/',jwt),env),'ben');assert.equal(await resolveAccessRole(request('/admin/crm/',jwt),env),null);assert.equal(await resolveAccessRole(request('/admin/jobs-fake',jwt),env),null);});
test('expired, missing-expiry, wrong issuer/audience and stale-session tokens are denied',async t=>{const env=setup(t),now=Math.floor(Date.now()/1000);for(const claims of [{exp:now-30},{exp:undefined},{iss:'https://attacker.example'},{aud:'another-app'},{iat:now-30000},{iat:now+120},{nbf:now+120}])assert.equal(await resolveAccessRole(request('/admin/crm/',await token(env,claims)),env),null);});
test('a bad signature never falls back to a valid Basic password',async t=>{const env=setup(t),jwt=await token(env),parts=jwt.split('.');parts[2]=(parts[2][0]==='A'?'B':'A')+parts[2].slice(1);const response=await worker.fetch(request('/admin/crm/',parts.join('.')),env);assert.equal(response.status,401);assert.equal(response.headers.get('WWW-Authenticate'),null);assert.equal((await worker.fetch(request('/admin/crm/'),env)).status,401);});
test('revocation cutoff rejects old sessions but permits subsequently issued sessions',async t=>{const env=setup(t),now=Math.floor(Date.now()/1000);env.ACCESS_REVOKE_BEFORE=String(now-60);assert.equal(await resolveAccessRole(request('/admin/crm/',await token(env,{iat:now-120})),env),null);assert.equal(await resolveAccessRole(request('/admin/crm/',await token(env)),env),'nathan');});
test('invalid managed configuration fails closed without affecting public enquiry configuration',async t=>{const env=setup(t);env.ACCESS_TEAM_DOMAIN='https://attacker.example';assert.equal((await worker.fetch(request('/admin/crm/'),env)).status,503);env.ADMIN_AUTH_MODE='typo';assert.equal((await worker.fetch(request('/admin/crm/'),env)).status,503);assert.equal((await worker.fetch(request('/api/enquiries/config'),env)).status,200);});
test('key-service redirects are rejected and token/credentials never enter the response',async t=>{const env=setup(t);t.mock.method(globalThis,'fetch',async()=>new Response(null,{status:302,headers:{Location:'https://attacker.example'}}));const jwt=await token(env),response=await worker.fetch(request('/admin/crm/',jwt),env);assert.equal(response.status,401);const body=await response.text();assert(!body.includes(jwt));assert(!body.includes(env.ADMIN_PASSWORD));});
