import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import {periods,metrics,parseWinInput,buildWins} from '../../src/lib/seo-quick-wins.js';
import {handleSeoWins} from '../../src/lib/seo-quick-wins-api.js';
const site='sc-domain:example.co.uk',page='https://example.co.uk/roofing/';
const row=(keys,clicks,impressions,position)=>({keys,clicks,impressions,position});
const input=parseWinInput({site});
function fixture(){return {currentTotals:[row([],100,2000,8)],previousTotals:[row([],200,3000,6)],currentPages:[row([page],10,1000,9)],previousPages:[row([page],30,1100,6),row(['https://example.co.uk/missing/'],20,200,7)],currentPairs:[row(['roofing cardiff',page],2,200,8)],previousPairs:[row(['roofing cardiff',page],10,250,5)],trend:[row(['2026-09-01'],3,20,9)]};}
function database(t){const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync('migrations/0009_seo_quick_wins.sql','utf8'));t.after(()=>sqlite.close());return {sqlite,prepare(sql){const s=sqlite.prepare(sql);return {args:[],bind(...args){this.args=args;return this;},async first(){return s.get(...this.args)||null;},async all(){return {results:s.all(...this.args)};},async run(){return {meta:s.run(...this.args)};}};},async batch(items){sqlite.exec('BEGIN');try{const r=[];for(const x of items)r.push(await x.run());sqlite.exec('COMMIT');return r;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};}
const request=(route,body)=>new Request('https://nc-digital.co.uk/admin/seo-quick-wins/api/'+route,{method:body?'POST':'GET',headers:{Origin:'https://nc-digital.co.uk','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
async function api(env,route,body){const r=await handleSeoWins(request(route,body),env),d=await r.json();assert.equal(r.status,200,JSON.stringify(d));return d;}
function provider(t,{failAuth=false,paginate=false}={}){const calls=[];t.mock.method(globalThis,'fetch',async(url,options)=>{calls.push({url,body:options.body});if(url.includes('oauth2'))return failAuth?Response.json({error:'invalid_grant'},{status:400}):Response.json({access_token:'secret-access'});assert.equal(options.headers.Authorization,'Bearer secret-access');if(url.endsWith('/sites'))return Response.json({siteEntry:[{siteUrl:site,permissionLevel:'siteOwner'}]});const q=JSON.parse(options.body);assert.equal(q.dataState,'final');assert.equal(q.type,'web');assert.equal(q.dimensionFilterGroups[0].filters[0].expression,'gbr');const prior=q.startDate===periods().previous.startDate,kind=q.dimensions.length===0?'Totals':q.dimensions.length===2?'Pairs':q.dimensions[0]==='page'?'Pages':'trend';if(paginate&&kind==='Pairs'&&!prior&&q.startRow===0)return Response.json({rows:Array.from({length:500},(_,i)=>row(['roofing '+i,page],2,200,8))});return Response.json({rows:kind==='trend'?fixture().trend:fixture()[(prior?'previous':'current')+kind]});});return calls;}
test('date windows are equal, inclusive, non-overlapping and use Pacific dates',()=>{const p=periods(28,new Date('2026-09-09T01:00:00Z'));assert.deepEqual(p.current,{startDate:'2026-08-09',endDate:'2026-09-05'});assert.deepEqual(p.previous,{startDate:'2026-07-12',endDate:'2026-08-08'});assert.equal((Date.parse(p.current.startDate)-Date.parse(p.previous.endDate))/86400000,1);});
test('null metrics and zero-impression positions do not become measured rankings',()=>{assert.equal(metrics(null),null);assert.equal(metrics(row([],0,0,0)).position,null);assert.equal(metrics(row([],1,100,null)).position,null);assert.equal(metrics(row([],2,100,9)).ctr,.02);});
test('opportunities use actual query/page pairs and independent page totals',()=>{const r=buildWins(input,periods(),fixture());assert.deepEqual(new Set(r.opportunities.map(x=>x.type)),new Set(['striking-distance','low-ctr','lost-position','declining-page']));assert.equal(r.pages[0].current.clicks,10);assert.equal(r.pages[0].queries.length,1);assert.ok(r.pages[0].opportunities.every(i=>typeof i==='number'));assert.equal(r.missingCurrent.length,1);assert.ok(!r.opportunities.some(o=>o.page.endsWith('/missing/')));});
test('missing prior rows stay unknown, brand filters exclude keyword signals only',()=>{const d=fixture();d.previousPairs=[];const r=buildWins(input,periods(),d);assert.equal(r.opportunities.find(o=>o.type==='striking-distance').previous,null);assert.ok(!r.opportunities.some(o=>o.type==='lost-position'));const branded=buildWins({...input,brands:['roofing']},periods(),d);assert.deepEqual(branded.opportunities.map(x=>x.type),['declining-page']);assert.equal(branded.overview.current.clicks,100);});
test('low-sample and small click declines do not create exaggerated signals',()=>{const d=fixture();d.currentPages=[row([page],8,100,10)];d.previousPages=[row([page],10,120,9)];d.currentPairs=[row(['roofing cardiff',page],0,5,9)];assert.equal(buildWins(input,periods(),d).opportunities.length,0);});
test('an explicit zero is different from a missing current page row',()=>{const d=fixture();d.currentPages=[row([page],0,0,0)];d.currentPairs=[];const r=buildWins(input,periods(),d);assert.equal(r.opportunities[0].type,'declining-page');assert.match(r.opportunities[0].reason,/100%/);assert.equal(r.opportunities[0].current.position,null);});
test('reports page through results, persist progress and reuse cached research',async t=>{const env={JOBS_DB:database(t),GOOGLE_GSC_CONFIG:JSON.stringify({client_id:'test',client_secret:'private',refresh_token:'private-refresh'})},calls=provider(t,{paginate:true});let r=await api(env,'start',{site});for(let i=0;r.status==='running'&&i<20;i++)r=await api(env,'advance',{id:r.id});assert.equal(r.status,'complete');assert.equal(r.report.coverage.currentPairs,501);const before=calls.length;const cached=await api(env,'start',{site});assert.equal(cached.cached,true);assert.equal(calls.length,before);assert.ok(!JSON.stringify(r).includes('private-refresh'));assert.ok(calls.some(x=>String(x.body||'').includes('"startRow":500')));await api(env,'task',{id:r.id,page,status:'in-progress',notes:'Review service headings'});assert.equal((await api(env,'tasks?site='+encodeURIComponent(site))).tasks[0].status,'in-progress');});
test('expired Google connection is actionable while saved history remains accessible',async t=>{const env={JOBS_DB:database(t),GOOGLE_GSC_CONFIG:'{}'};provider(t,{failAuth:true});const status=await api(env,'sites');assert.equal(status.connected,false);assert.match(status.message,/fresh Search Console sign-in/);assert.equal((await api(env,'history')).reports.length,0);});
test('concurrent starts cannot duplicate reports; property and origin checks enforce access',async t=>{const env={JOBS_DB:database(t),GOOGLE_GSC_CONFIG:'{}'};provider(t);const [a,b]=await Promise.all([handleSeoWins(request('start',{site}),env),handleSeoWins(request('start',{site}),env)]);assert.deepEqual([a.status,b.status].sort(),[200,409]);const r=await a.json();await api(env,'stop',{id:r.id});const bad=await handleSeoWins(request('start',{site:'sc-domain:other.co.uk'}),env);assert.equal(bad.status,403);const cross=new Request('https://nc-digital.co.uk/admin/seo-quick-wins/api/start',{method:'POST',headers:{Origin:'https://other.co.uk'},body:JSON.stringify({site})});assert.equal((await handleSeoWins(cross,env)).status,403);});

